import { DEFAULT_DELIVERY } from "@/lib/constants";

export const CATALOG_VERSION = "10-deliver-anywhere";

export type SeedCategory = {
  id: string;
  parentId: string | null;
  name: string;
  description: string;
  imageUrl: string;
  sortOrder: number;
};

export type SeedProduct = {
  id: string;
  categoryId: string;
  name: string;
  description: string;
  price: number;
  compareAt?: number;
  images: string[];
  specs: Record<string, string>;
  colors: { name: string; hex: string }[];
  sizes: string[];
  dimensions: string;
  material: string;
  stock: number;
  warranty: string;
  featured?: boolean;
  bestseller?: boolean;
  newArrival?: boolean;
  specialOffer?: boolean;
};

export type SeedBanner = {
  title: string;
  subtitle: string;
  imageUrl: string;
  ctaText: string;
  ctaHref: string;
  sortOrder: number;
};

export const SEED_CATEGORIES: SeedCategory[] = [
  { id: "furniture", parentId: null, name: "Furniture", description: "Sofas, beds, tables, storage and lighting for the Abuja home.", imageUrl: "/banners/living-hero.jpg", sortOrder: 1 },
  { id: "appliances", parentId: null, name: "Appliances", description: "Refrigeration, laundry, cooking, cooling and small kitchen machines.", imageUrl: "/banners/kitchen-hero.jpg", sortOrder: 2 },
  { id: "electronics", parentId: null, name: "Electronics", description: "Televisions, sound, speakers and the accessories that finish a room.", imageUrl: "/products/tv-65.jpg", sortOrder: 3 },

  { id: "sofas", parentId: "furniture", name: "Sofas and couches", description: "3+2+1 sitting-room sets, corners, U-shapes, Chesterfields, sofa beds and single sofas.", imageUrl: "/products/set-chenille-321.jpg", sortOrder: 1 },
  { id: "beds", parentId: "furniture", name: "Beds", description: "Wood and upholstered bed frames. Mattresses are sold separately.", imageUrl: "/products/bed-cedar.jpg", sortOrder: 2 },
  { id: "mattresses", parentId: "furniture", name: "Mattresses", description: "Pocket-spring, foam and latex mattresses.", imageUrl: "/products/mattress.jpg", sortOrder: 3 },
  { id: "wardrobes", parentId: "furniture", name: "Wardrobes", description: "Sliding, mirrored, hinged and open hanging wardrobes.", imageUrl: "/products/wardrobe-mirror.jpg", sortOrder: 4 },
  { id: "dining-sets", parentId: "furniture", name: "Dining sets", description: "Oak, marble and stone tables sold with their chairs, from four seats to eight.", imageUrl: "/products/dining-marble-white.jpg", sortOrder: 5 },
  { id: "tables", parentId: "furniture", name: "Tables", description: "Centre tables, coffee tables, consoles and bedside pairs.", imageUrl: "/products/bedside-pair.jpg", sortOrder: 6 },
  { id: "chairs", parentId: "furniture", name: "Chairs", description: "Royal chairs, wingbacks, Chesterfield armchairs, dining carvers, lounge chairs, rockers, stools and benches. Sofas are a separate category.", imageUrl: "/products/chair-royal.jpg", sortOrder: 7 },
  { id: "tv-stands", parentId: "furniture", name: "TV stands", description: "Wall-mounted media units and floor-standing consoles. Televisions are sold separately.", imageUrl: "/products/tvstand.jpg", sortOrder: 8 },
  { id: "cabinets", parentId: "furniture", name: "Cabinets", description: "Sideboards, kitchen pantry cabinets and glass display cabinets.", imageUrl: "/products/sideboard-cab.jpg", sortOrder: 9 },
  { id: "office-furniture", parentId: "furniture", name: "Home and office furniture", description: "Writing desks, standing desks, bookcases, workstations and task chairs.", imageUrl: "/products/bookshelf.jpg", sortOrder: 10 },
  { id: "lighting", parentId: "furniture", name: "Lighting", description: "Pendants, floor lamps, table lamps and wall sconces.", imageUrl: "/products/pendant-drum.jpg", sortOrder: 11 },
  { id: "bedroom-storage", parentId: "furniture", name: "Dressers and vanities", description: "Chests of drawers and dressing tables with a mirror and stool.", imageUrl: "/products/dressing-table.jpg", sortOrder: 12 },

  { id: "refrigerators", parentId: "appliances", name: "Refrigerators", description: "Top-freezer double-door, French-door, side-by-side and compact fridges.", imageUrl: "/products/fridge-black.jpg", sortOrder: 1 },
  { id: "freezers", parentId: "appliances", name: "Freezers", description: "Chest freezers and single-door upright freezers. No fridge compartment.", imageUrl: "/products/freezer-slim.jpg", sortOrder: 2 },
  { id: "washing-machines", parentId: "appliances", name: "Washing machines", description: "Front-load washers, top-load washers, washer-dryer combos, and stacked pairs.", imageUrl: "/products/washer-combo.jpg", sortOrder: 3 },
  { id: "cookers", parentId: "appliances", name: "Cookers", description: "Freestanding gas cookers and wider ranges, each with an oven.", imageUrl: "/products/cooker-five.jpg", sortOrder: 4 },
  { id: "microwaves", parentId: "appliances", name: "Microwaves", description: "Countertop microwave ovens, black or white.", imageUrl: "/products/microwave-white.jpg", sortOrder: 5 },
  { id: "air-conditioners", parentId: "appliances", name: "Air conditioners", description: "Wall-mounted split indoor units. The outdoor condenser is included with each set.", imageUrl: "/products/split-ac.jpg", sortOrder: 6 },
  { id: "fans", parentId: "appliances", name: "Fans", description: "Pedestal, desk, ceiling and tower fans.", imageUrl: "/products/stand-fan.jpg", sortOrder: 7 },
  { id: "other-appliances", parentId: "appliances", name: "Other home appliances", description: "Blenders, kettles, rice cookers, irons, dispensers, air fryers, toaster ovens, espresso machines, dishwashers and robot vacuums.", imageUrl: "/products/rice-cooker.jpg", sortOrder: 8 },

  { id: "televisions", parentId: "electronics", name: "Televisions", description: "32, 43, 55, 65 and 75 inch smart televisions. Sound is sold separately.", imageUrl: "/products/tv-32.jpg", sortOrder: 1 },
  { id: "sound-systems", parentId: "electronics", name: "Sound systems", description: "Soundbars, subwoofers, satellite speakers, bookshelf pairs and floor-standing pairs. Not televisions.", imageUrl: "/products/speakers-floor.jpg", sortOrder: 2 },
  { id: "speakers", parentId: "electronics", name: "Speakers", description: "Portable speakers, from a compact Bluetooth unit to a wheeled party speaker.", imageUrl: "/products/speaker-bt.jpg", sortOrder: 3 },
  { id: "home-entertainment", parentId: "electronics", name: "Home entertainment", description: "A television and its soundbar sold together as one set.", imageUrl: "/products/cinema-55.jpg", sortOrder: 4 },
  { id: "accessories", parentId: "electronics", name: "Electronics accessories", description: "Headphones, earbuds, cables, surge protection and wall mounts.", imageUrl: "/products/earbuds.jpg", sortOrder: 5 },
  { id: "other-electronics", parentId: "electronics", name: "Other consumer electronics", description: "Projectors, mesh Wi-Fi and streaming pucks. Not televisions and not speakers.", imageUrl: "/products/streamer.jpg", sortOrder: 6 },
];

const w12 = "12 months manufacturer warranty, supported at our Karu showroom.";
const w24 = "24 months manufacturer warranty with in-store support.";
const wFrame = "5-year frame warranty, 12 months on upholstery.";

export const SEED_PRODUCTS: SeedProduct[] = [
  {
    id: "aso-rock-sofa",
    categoryId: "sofas",
    name: "Greige Linen Three-Seater",
    description: "Three-seater in greige linen with loose back cushions, track arms and light oak legs. Kiln-dried hardwood frame and high-resilience foam.",
    price: 425000,
    compareAt: 495000,
    images: ["/products/sofa-linen.jpg", "/banners/living-hero.jpg"],
    specs: { Seating: "3-seater", Frame: "Kiln-dried hardwood", Fill: "High-resilience foam", Legs: "Oak" },
    colors: [{ name: "Greige linen", hex: "#C4B7A6" }, { name: "Stone", hex: "#D9D1C4" }],
    sizes: ["3-seater"],
    dimensions: "220 × 95 × 82 cm",
    material: "Linen blend on hardwood",
    stock: 6,
    warranty: wFrame,
    featured: true,
    bestseller: true,
    specialOffer: true,
  },
  {
    id: "karu-velvet-loveseat",
    categoryId: "sofas",
    name: "Forest Velvet Loveseat",
    description: "Two-seater in forest velvet with rolled arms and dark walnut feet. A compact sofa for a smaller sitting room.",
    price: 285000,
    images: ["/products/sofa-velvet.jpg"],
    specs: { Seating: "2-seater", Legs: "Walnut", Style: "Rolled arm" },
    colors: [{ name: "Forest velvet", hex: "#1E3A2F" }],
    sizes: ["2-seater"],
    dimensions: "162 × 88 × 80 cm",
    material: "Cotton velvet, walnut legs",
    stock: 4,
    warranty: wFrame,
    featured: true,
    newArrival: true,
  },
  {
    id: "garki-leather-sofa",
    categoryId: "sofas",
    name: "Cognac Leather Three-Seater",
    description: "Three-seater in cognac full-grain leather, low profile, wide block arms and dark walnut feet. Made for air-conditioned sitting rooms.",
    price: 610000,
    images: ["/products/leather-sofa.jpg"],
    specs: { Seating: "3-seater", Leather: "Full grain", Feet: "Walnut block" },
    colors: [{ name: "Cognac", hex: "#8A4B24" }],
    sizes: ["3-seater"],
    dimensions: "230 × 96 × 78 cm",
    material: "Full-grain leather, hardwood",
    stock: 3,
    warranty: wFrame,
    bestseller: true,
  },
  {
    id: "asokoro-sectional",
    categoryId: "sofas",
    name: "Pale Linen Sectional",
    description: "L-shaped sectional in pale linen with a right-hand chaise, loose back cushions and a round coffee table shown for scale. Seats a full Sunday gathering.",
    price: 890000,
    compareAt: 980000,
    images: ["/products/sectional.jpg"],
    specs: { Layout: "L-shape, right chaise", Seating: "4–5", Fill: "Foam and fibre" },
    colors: [{ name: "Pale linen", hex: "#E4D8C8" }],
    sizes: ["Right chaise"],
    dimensions: "290 × 170 × 84 cm",
    material: "Linen blend, hardwood frame",
    stock: 2,
    warranty: wFrame,
    featured: true,
    specialOffer: true,
  },
  {
    id: "nyanya-teal-sofa",
    categoryId: "sofas",
    name: "Teal Velvet Three-Seater",
    description: "Three-seater in teal velvet with square arms, bolster cushions and tapered oak legs. A single deep seat cushion across the front.",
    price: 365000,
    images: ["/products/sofa-green.jpg", "/banners/hero.jpg"],
    specs: { Seating: "3-seater", Arms: "Square with bolsters", Legs: "Oak" },
    colors: [{ name: "Teal velvet", hex: "#1F6F66" }],
    sizes: ["3-seater"],
    dimensions: "210 × 88 × 80 cm",
    material: "Cotton velvet, oak legs",
    stock: 4,
    warranty: wFrame,
    newArrival: true,
  },
  {
    id: "cedar-king-bed",
    categoryId: "beds",
    name: "Cedar King Bed Frame",
    description: "King platform bed in natural oak-toned wood with a tall panelled headboard and a slatted base. No box spring. Fits a 6 × 6 mattress, sold separately.",
    price: 310000,
    images: ["/products/bed-cedar.jpg"],
    specs: { Size: "King 6×6", Base: "Platform slats", Headboard: "Panelled wood" },
    colors: [{ name: "Natural oak tone", hex: "#C19A6B" }],
    sizes: ["6×6 King"],
    dimensions: "200 × 190 × 120 cm",
    material: "Solid wood and veneer",
    stock: 5,
    warranty: "5-year structural warranty.",
    featured: true,
    newArrival: true,
  },
  {
    id: "maitama-queen-bed",
    categoryId: "beds",
    name: "Charcoal Bouclé Queen Bed",
    description: "Queen bed with a winged headboard and upholstered base in charcoal bouclé. Shown dressed in ivory linen. Mattress not included.",
    price: 265000,
    images: ["/products/bed-boucle.jpg"],
    specs: { Size: "Queen 5×6", Headboard: "Winged bouclé", Base: "Upholstered" },
    colors: [{ name: "Charcoal bouclé", hex: "#3A3836" }],
    sizes: ["5×6 Queen"],
    dimensions: "175 × 210 × 128 cm",
    material: "Bouclé fabric, hardwood frame",
    stock: 4,
    warranty: wFrame,
  },
  {
    id: "jabi-platform-bed",
    categoryId: "beds",
    name: "Walnut Platform Bed",
    description: "Low walnut platform bed with a simple horizontal headboard and a deep wood base. King size, slatted, no box spring. Mattress sold separately.",
    price: 285000,
    images: ["/products/platform-bed.jpg"],
    specs: { Size: "King 6×6", Base: "Platform slats", Profile: "Low" },
    colors: [{ name: "Walnut", hex: "#6B4226" }],
    sizes: ["6×6 King", "5×6 Queen"],
    dimensions: "210 × 195 × 95 cm",
    material: "Walnut veneer, solid wood rails",
    stock: 4,
    warranty: "5-year structural warranty.",
    newArrival: true,
    featured: true,
  },
  {
    id: "orthorest-king",
    categoryId: "mattresses",
    name: "OrthoRest Pocket Spring Mattress — King",
    description: "Medium-firm pocket-spring mattress with a diamond-quilted ivory cover. Ten-inch profile, breathable ticking, no memory-foam heat trap.",
    price: 195000,
    images: ["/products/mattress.jpg"],
    specs: { Profile: "10 inch", Feel: "Medium-firm", Core: "Pocket coil", Cover: "Diamond quilt" },
    colors: [{ name: "Ivory", hex: "#F3EEE6" }],
    sizes: ["6×6 King", "5×6 Queen"],
    dimensions: "200 × 180 × 25 cm",
    material: "Pocket springs, quilted knit",
    stock: 12,
    warranty: "10-year limited mattress warranty.",
    bestseller: true,
  },
  {
    id: "cloudfoam-queen",
    categoryId: "mattresses",
    name: "CloudFoam Queen Mattress",
    description: "Plush high-density foam mattress with a thick pillow-top edge and a smooth ivory cover. Queen 5 × 6. Softer than the OrthoRest.",
    price: 145000,
    compareAt: 185000,
    images: ["/products/foam-mattress.jpg"],
    specs: { Profile: "11 inch", Feel: "Plush pillow-top", Core: "HD foam" },
    colors: [{ name: "Ivory", hex: "#F3EEE6" }],
    sizes: ["5×6 Queen"],
    dimensions: "190 × 150 × 28 cm",
    material: "High-density foam",
    stock: 9,
    warranty: "5-year limited mattress warranty.",
    specialOffer: true,
  },
  {
    id: "latexrest-king",
    categoryId: "mattresses",
    name: "LatexRest Natural Latex Mattress — King",
    description: "Twelve-inch latex mattress. Pin-dot perforated top, honey-coloured latex sidewall, ivory cover. Cooler and more supportive than the CloudFoam.",
    price: 340000,
    images: ["/products/latex-mattress.jpg"],
    specs: { Profile: "12 inch", Feel: "Medium", Core: "Natural latex", Cover: "Pin-dot knit" },
    colors: [{ name: "Ivory / honey", hex: "#E6D3B0" }],
    sizes: ["6×6 King"],
    dimensions: "200 × 180 × 30 cm",
    material: "Natural latex, knit cover",
    stock: 5,
    warranty: "10-year limited mattress warranty.",
    featured: true,
    newArrival: true,
  },
  {
    id: "walnut-wardrobe",
    categoryId: "wardrobes",
    name: "Walnut Sliding Wardrobe",
    description: "Four-door sliding wardrobe in walnut veneer. The second door is a full-length mirror. Hanging rail and shelves behind the solid doors.",
    price: 340000,
    images: ["/products/wardrobe.jpg"],
    specs: { Doors: "4 sliding", Mirror: "One full-height panel", Interior: "Rail and shelves" },
    colors: [{ name: "Walnut", hex: "#5C4033" }],
    sizes: ["200 cm"],
    dimensions: "200 × 60 × 215 cm",
    material: "Walnut veneer, engineered wood",
    stock: 4,
    warranty: w24,
    featured: true,
  },
  {
    id: "linen-white-wardrobe",
    categoryId: "wardrobes",
    name: "Ivory Hinged Wardrobe",
    description: "Two-door hinged wardrobe in warm white with shaker panels. One door opens onto a hanging rail and shelves. No mirror.",
    price: 195000,
    images: ["/products/white-wardrobe.jpg"],
    specs: { Doors: "2 hinged", Mirror: "None", Interior: "Rail and shelves" },
    colors: [{ name: "Warm white", hex: "#F4F0EA" }],
    sizes: ["100 cm"],
    dimensions: "100 × 58 × 200 cm",
    material: "Painted engineered wood",
    stock: 6,
    warranty: w12,
    newArrival: true,
  },
  {
    id: "oak-dining-six",
    categoryId: "dining-sets",
    name: "Oak 6-Seater Dining Set",
    description: "Rectangular oak dining table with a pedestal base and six greige upholstered chairs with oak legs. Sold only as the complete set.",
    price: 380000,
    images: ["/products/dining.jpg"],
    specs: { Seats: "6", Table: "Oak pedestal", Chairs: "Greige upholstered" },
    colors: [{ name: "Oak / greige", hex: "#C4B7A6" }],
    sizes: ["6-seater"],
    dimensions: "Table 180 × 90 × 76 cm",
    material: "Oak veneer, fabric chairs",
    stock: 5,
    warranty: w24,
    bestseller: true,
    featured: true,
  },
  {
    id: "compact-dining-four",
    categoryId: "dining-sets",
    name: "Compact 4-Seater Dining Set",
    description: "Smaller oak table with exactly four greige upholstered chairs. Rounded corners, sized for apartment dining. Sold as a set.",
    price: 215000,
    images: ["/products/dining-4.jpg"],
    specs: { Seats: "4", Chairs: "Greige upholstered", Shape: "Rectangle" },
    colors: [{ name: "Oak / greige", hex: "#E8DCC8" }],
    sizes: ["4-seater"],
    dimensions: "Table 140 × 80 × 76 cm",
    material: "Oak veneer, fabric chairs",
    stock: 7,
    warranty: w12,
    newArrival: true,
  },
  {
    id: "live-edge-table",
    categoryId: "tables",
    name: "Live Edge Centre Table",
    description: "Solid wood slab coffee table with a natural live edge and black metal hairpin legs. Each top varies slightly in grain.",
    price: 95000,
    images: ["/products/table-live.jpg"],
    specs: { Top: "Live-edge hardwood", Legs: "Black hairpin" },
    colors: [{ name: "Natural wood", hex: "#8B5A2B" }],
    sizes: ["120 cm"],
    dimensions: "120 × 60 × 42 cm",
    material: "Hardwood slab, steel",
    stock: 8,
    warranty: w12,
    newArrival: true,
    featured: true,
  },
  {
    id: "marble-round-table",
    categoryId: "tables",
    name: "Marble Round Coffee Table",
    description: "Round white marble top on a slim brass-finished metal base. A centre table, not a dining table.",
    price: 165000,
    images: ["/products/marble-table.jpg"],
    specs: { Top: "White marble", Base: "Brass-finish metal", Shape: "Round" },
    colors: [{ name: "White / brass", hex: "#E7E1D6" }],
    sizes: ["90 cm"],
    dimensions: "90 × 90 × 40 cm",
    material: "Marble, metal",
    stock: 5,
    warranty: w12,
    featured: true,
  },
  {
    id: "oak-console",
    categoryId: "tables",
    name: "Oak Hall Console",
    description: "Slim oak console with one drawer and tapered legs. For a hallway or behind a sofa, not a dining table.",
    price: 78000,
    images: ["/products/console.jpg"],
    specs: { Drawers: "1", Use: "Hall or sofa back" },
    colors: [{ name: "Oak", hex: "#C4A574" }],
    sizes: ["120 cm"],
    dimensions: "120 × 36 × 78 cm",
    material: "Oak veneer",
    stock: 7,
    warranty: w12,
    newArrival: true,
  },
  {
    id: "boucle-accent-chair",
    categoryId: "chairs",
    name: "Bouclé Accent Chair",
    description: "Curved lounge chair in cream bouclé with dark oak legs. One chair. A throw is shown for scale and is not included.",
    price: 125000,
    images: ["/products/chair-boucle.jpg"],
    specs: { Style: "Lounge", Legs: "Dark oak", Sold: "Single" },
    colors: [{ name: "Cream bouclé", hex: "#EDE4D4" }],
    sizes: ["Single"],
    dimensions: "78 × 82 × 78 cm",
    material: "Bouclé, oak",
    stock: 6,
    warranty: wFrame,
    featured: true,
  },
  {
    id: "dining-chair-pair",
    categoryId: "chairs",
    name: "Upholstered Dining Chairs — Pair",
    description: "Two greige linen dining chairs with curved backs and tapered oak legs. Sold as a pair. They match the compact dining set if you need extras.",
    price: 68000,
    images: ["/products/dining-chairs.jpg"],
    specs: { Pack: "2 chairs", Legs: "Oak", Back: "Curved upholstered" },
    colors: [{ name: "Greige", hex: "#E6DCCE" }],
    sizes: ["Pair"],
    dimensions: "Each 48 × 54 × 82 cm",
    material: "Linen blend, oak",
    stock: 14,
    warranty: w12,
  },
  {
    id: "wuse-tufted-chair",
    categoryId: "chairs",
    name: "Ivory Button-Tufted Lounge Chair",
    description: "Ivory button-tufted lounge chair with a rounded back and white turned bobbin legs. One chair. Not a dining chair.",
    price: 145000,
    images: ["/products/chair-mid.jpg"],
    specs: { Style: "Tufted lounge", Legs: "Turned, painted white", Sold: "Single" },
    colors: [{ name: "Ivory", hex: "#F4EFE6" }],
    sizes: ["Single"],
    dimensions: "72 × 70 × 78 cm",
    material: "Velvet, painted wood",
    stock: 5,
    warranty: wFrame,
  },
  {
    id: "karu-bar-stool",
    categoryId: "chairs",
    name: "Washed Oak Bar Stool",
    description: "Backless counter stool in washed pale oak, with a handhold slot in the seat and a foot rail. Sold singly. Seat height suits a kitchen counter, not a dining table.",
    price: 42000,
    images: ["/products/chair-dining.jpg"],
    specs: { Type: "Bar stool", Back: "None", Finish: "Washed oak" },
    colors: [{ name: "Washed oak", hex: "#E4DCCF" }],
    sizes: ["Counter height"],
    dimensions: "Seat 35 × 35 cm, height 65 cm",
    material: "Solid oak",
    stock: 16,
    warranty: w12,
    bestseller: true,
  },
  {
    id: "smoked-tv-stand",
    categoryId: "tv-stands",
    name: "Smoked Oak Floating Media Unit",
    description: "Wall-mounted media unit in smoked oak. Two sliding doors and an open centre with two shelves. Holds a 55 to 65 inch television on top. Not a floor-standing cabinet.",
    price: 145000,
    images: ["/products/tvstand.jpg"],
    specs: { Mount: "Wall floating", Width: "180 cm", Storage: "2 doors, open shelves" },
    colors: [{ name: "Smoked oak", hex: "#4A4038" }],
    sizes: ["180 cm"],
    dimensions: "180 × 32 × 40 cm",
    material: "Oak veneer, engineered wood",
    stock: 7,
    warranty: w12,
    bestseller: true,
  },
  {
    id: "wuse-cabinet",
    categoryId: "cabinets",
    name: "Walnut Sideboard",
    description: "Low sideboard in walnut with two cupboard doors and three drawers, brass knobs. For a dining room or living room, not a kitchen pantry.",
    price: 168000,
    images: ["/products/sideboard-cab.jpg"],
    specs: { Doors: "2", Drawers: "3", Hardware: "Brass knobs" },
    colors: [{ name: "Walnut", hex: "#5C4033" }],
    sizes: ["160 cm"],
    dimensions: "160 × 45 × 78 cm",
    material: "Walnut veneer, engineered wood",
    stock: 6,
    warranty: w12,
    featured: true,
  },
  {
    id: "kitchen-cabinet",
    categoryId: "cabinets",
    name: "Kitchen Pantry Cabinet",
    description: "Tall warm-white pantry with two full-height doors and adjustable shelves. For dry goods. It is a freestanding cabinet, not a fitted kitchen run.",
    price: 89000,
    images: ["/products/pantry.jpg"],
    specs: { Doors: "2 hinged", Shelves: "Adjustable", Type: "Freestanding pantry" },
    colors: [{ name: "Warm white", hex: "#F4F0EA" }],
    sizes: ["80 cm wide"],
    dimensions: "80 × 40 × 190 cm",
    material: "Painted engineered wood",
    stock: 8,
    warranty: w12,
  },
  {
    id: "jabi-desk",
    categoryId: "office-furniture",
    name: "Walnut Executive Desk",
    description: "Walnut writing desk with two drawers on the right and a brown leather writing mat. No pedestal return. Chair sold separately.",
    price: 185000,
    images: ["/products/exec-desk.jpg"],
    specs: { Drawers: "2, right side", Top: "Walnut with leather mat", Chair: "Not included" },
    colors: [{ name: "Walnut", hex: "#5C4033" }],
    sizes: ["150 cm"],
    dimensions: "150 × 70 × 76 cm",
    material: "Walnut veneer, leather mat",
    stock: 5,
    warranty: w12,
    newArrival: true,
  },
  {
    id: "home-workstation",
    categoryId: "office-furniture",
    name: "Home Office Workstation",
    description: "Pale oak desktop on white trestle legs, with a black desk mat and an open oak shelf standing beside it. Laptop in the photograph is not included.",
    price: 165000,
    images: ["/products/workstation.jpg"],
    specs: { Includes: "Desk and open shelf", Legs: "White trestle", Chair: "Not included" },
    colors: [{ name: "Oak / white", hex: "#E7E0D4" }],
    sizes: ["Standard"],
    dimensions: "Desk 140 × 70 × 75 cm",
    material: "Oak top, painted trestles",
    stock: 4,
    warranty: w12,
  },
  {
    id: "karu-task-chair",
    categoryId: "office-furniture",
    name: "Charcoal Mesh Task Chair",
    description: "Charcoal ergonomic task chair with a mesh back, padded seat, adjustable arms and a five-star base. An office chair, not a lounge chair.",
    price: 95000,
    images: ["/products/task-chair.jpg"],
    specs: { Back: "Mesh", Base: "Five-star with casters", Arms: "Adjustable" },
    colors: [{ name: "Charcoal", hex: "#3A3A3A" }],
    sizes: ["Standard"],
    dimensions: "Seat height 45–55 cm",
    material: "Mesh, foam, metal base",
    stock: 9,
    warranty: w12,
    bestseller: true,
  },
  {
    id: "aria-pendant",
    categoryId: "lighting",
    name: "Aria Cluster Pendant",
    description: "Five clear glass globes on brass arms, hung from one ceiling canopy. A dining or entrance light, not a desk lamp. Hardwired. Installation in Abuja can be arranged.",
    price: 135000,
    images: ["/products/pendant.jpg"],
    specs: { Globes: "5", Finish: "Brass and clear glass", Fitting: "Hardwired" },
    colors: [{ name: "Brass / clear", hex: "#C4B8A5" }],
    sizes: ["Cluster of 5"],
    dimensions: "Drop about 70 cm",
    material: "Glass, brass-finished metal",
    stock: 3,
    warranty: w12,
    newArrival: true,
    featured: true,
  },
  {
    id: "arc-floor-lamp",
    categoryId: "lighting",
    name: "Arc Brass Floor Lamp",
    description: "Single floor lamp with a round base, a slim brass arc and an off-white linen drum shade. One lamp. Bulb included.",
    price: 72000,
    images: ["/products/floor-lamp.jpg"],
    specs: { Type: "Floor lamp", Shade: "Linen drum", Bulb: "Included" },
    colors: [{ name: "Brass / ivory", hex: "#C4B08A" }],
    sizes: ["Single"],
    dimensions: "Height 160 cm",
    material: "Metal, linen shade",
    stock: 8,
    warranty: w12,
  },
  {
    id: "ceramic-table-lamp",
    categoryId: "lighting",
    name: "Ceramic Table Lamp",
    description: "Table lamp with a cream stoneware base and a linen drum shade. For a bedside or console. One lamp.",
    price: 38000,
    images: ["/products/table-lamp.jpg"],
    specs: { Type: "Table lamp", Base: "Stoneware", Shade: "Linen" },
    colors: [{ name: "Cream", hex: "#EFE6D8" }],
    sizes: ["Single"],
    dimensions: "Height 48 cm",
    material: "Ceramic, linen, metal",
    stock: 12,
    warranty: w12,
    newArrival: true,
  },
  {
    id: "frostpeak-fridge",
    categoryId: "refrigerators",
    name: "FrostPeak 265L Double-Door Refrigerator",
    description: "Household frost-free refrigerator in brushed steel. Smaller top freezer door, larger bottom fridge door, both solid metal. 265 litres. Not a commercial display cooler.",
    price: 285000,
    compareAt: 330000,
    images: ["/products/fridge-dd.jpg"],
    specs: { Capacity: "265 litres", Layout: "Top freezer, bottom fridge", Doors: "2 solid", Energy: "A+" },
    colors: [{ name: "Brushed steel", hex: "#C5C7C4" }],
    sizes: ["265L"],
    dimensions: "60 × 65 × 170 cm",
    material: "Steel cabinet, glass shelves",
    stock: 8,
    warranty: w24,
    featured: true,
    bestseller: true,
    specialOffer: true,
  },
  {
    id: "noir-french-fridge",
    categoryId: "refrigerators",
    name: "Noire 450L French-Door Refrigerator",
    description: "Matte black French-door refrigerator. Two upper fridge doors and one wide bottom freezer drawer. About 450 litres, for a family kitchen.",
    price: 620000,
    images: ["/products/fridge-frenchdoor.jpg"],
    specs: { Capacity: "450 litres", Layout: "French door, bottom freezer", Finish: "Matte black" },
    colors: [{ name: "Matte black", hex: "#1C1C1C" }],
    sizes: ["450L"],
    dimensions: "83 × 73 × 178 cm",
    material: "Steel cabinet",
    stock: 3,
    warranty: w24,
    featured: true,
    newArrival: true,
  },
  {
    id: "harbour-mint-fridge",
    categoryId: "refrigerators",
    name: "Harbour Mint Compact Refrigerator",
    description: "Single-door compact refrigerator in glossy mint, with a chrome handle and rounded top. A small retro fridge, not a family double-door.",
    price: 185000,
    images: ["/products/fridge.jpg"],
    specs: { Type: "Single door compact", Finish: "Gloss mint", Freezer: "Small interior compartment" },
    colors: [{ name: "Mint", hex: "#7FDBD4" }],
    sizes: ["Compact"],
    dimensions: "60 × 65 × 130 cm",
    material: "Enamelled steel",
    stock: 2,
    warranty: w12,
  },
  {
    id: "chillvault-freezer",
    categoryId: "freezers",
    name: "ChillVault 200L Chest Freezer",
    description: "White chest freezer with the lid closed, a front lock and an interior basket. 200 litres. It is a freezer only, not a fridge.",
    price: 245000,
    images: ["/products/chest-freezer.jpg"],
    specs: { Capacity: "200 litres", Type: "Chest", Baskets: "1" },
    colors: [{ name: "White", hex: "#F4F4F2" }],
    sizes: ["200L"],
    dimensions: "90 × 55 × 85 cm",
    material: "Steel cabinet",
    stock: 6,
    warranty: w24,
    bestseller: true,
  },
  {
    id: "chillvault-upright",
    categoryId: "freezers",
    name: "ChillVault 250L Upright Freezer",
    description: "White upright freezer with one solid door and pull-out drawers inside. 250 litres. No fridge compartment.",
    price: 310000,
    images: ["/products/upright-freezer.jpg"],
    specs: { Capacity: "250 litres", Type: "Upright", Door: "1 solid" },
    colors: [{ name: "White", hex: "#F4F4F2" }],
    sizes: ["250L"],
    dimensions: "60 × 65 × 170 cm",
    material: "Steel cabinet",
    stock: 4,
    warranty: w24,
    newArrival: true,
  },
  {
    id: "aquacycle-washer",
    categoryId: "washing-machines",
    name: "AquaCycle 8kg Front Load Washer",
    description: "White front-loading washing machine, 8 kg, round glass door, inverter motor, 15 programmes, 1200 rpm spin. Shown empty.",
    price: 365000,
    images: ["/products/washer-fl.jpg"],
    specs: { Capacity: "8 kg", Type: "Front load", Motor: "Inverter", Spin: "1200 rpm" },
    colors: [{ name: "White", hex: "#F4F4F2" }],
    sizes: ["8 kg"],
    dimensions: "60 × 58 × 85 cm",
    material: "Steel, glass door",
    stock: 5,
    warranty: w24,
    featured: true,
  },
  {
    id: "aquacycle-topload",
    categoryId: "washing-machines",
    name: "AquaCycle 10kg Top Load Washer",
    description: "White top-loading washing machine, 10 kg, lid on top, control panel at the rear. For households that prefer not to bend to a front door.",
    price: 245000,
    images: ["/products/washer-tl.jpg"],
    specs: { Capacity: "10 kg", Type: "Top load", Lid: "Top" },
    colors: [{ name: "White", hex: "#F4F4F2" }],
    sizes: ["10 kg"],
    dimensions: "62 × 63 × 100 cm",
    material: "Steel and plastic lid",
    stock: 6,
    warranty: w24,
    specialOffer: true,
  },
  {
    id: "flamehaus-cooker",
    categoryId: "cookers",
    name: "FlameHaus 4-Burner Gas Cooker",
    description: "Freestanding stainless cooker. Four gas burners, cast-iron grates, glass lid, and an oven below. LPG. It stands on the floor — it is not a built-in hob.",
    price: 155000,
    images: ["/products/gas-cooker.jpg"],
    specs: { Burners: "4 gas", Oven: "Yes", Fuel: "LPG", Type: "Freestanding" },
    colors: [{ name: "Stainless", hex: "#C5C7C4" }],
    sizes: ["60 cm"],
    dimensions: "60 × 60 × 85 cm",
    material: "Stainless steel, enamel oven",
    stock: 7,
    warranty: w12,
    bestseller: true,
    featured: true,
  },
  {
    id: "heatwave-microwave",
    categoryId: "microwaves",
    name: "HeatWave 25L Microwave",
    description: "Black countertop microwave, about 25 litres, with a dial and grill function. Sits on a worktop. Not a built-in oven.",
    price: 72000,
    images: ["/products/microwave-ct.jpg"],
    specs: { Capacity: "25 litres", Grill: "Yes", Power: "900 W", Type: "Countertop" },
    colors: [{ name: "Black", hex: "#1A1A1A" }],
    sizes: ["25L"],
    dimensions: "48 × 40 × 29 cm",
    material: "Steel cavity",
    stock: 11,
    warranty: w12,
  },
  {
    id: "breezeline-ac",
    categoryId: "air-conditioners",
    name: "BreezeLine Split Air Conditioner",
    description: "Wall-mounted split indoor unit in white, with the outdoor condenser supplied. Copper piping and a remote. Choose 1 HP, 1.5 HP or 2 HP at checkout. Installation across Abuja can be arranged.",
    price: 295000,
    images: ["/products/split-ac.jpg"],
    specs: { Type: "Split, wall indoor unit", Refrigerant: "R32", Includes: "Indoor unit, outdoor unit, remote" },
    colors: [{ name: "White", hex: "#F2F2F0" }],
    sizes: ["1.5 HP", "1 HP", "2 HP"],
    dimensions: "Indoor about 80 × 20 × 29 cm",
    material: "ABS indoor, copper coil",
    stock: 6,
    warranty: w24,
    featured: true,
    newArrival: true,
  },
  {
    id: "breezeline-fan",
    categoryId: "fans",
    name: "BreezeLine 18-inch Pedestal Fan",
    description: "Black standing fan with an 18-inch head, slim pedestal, round base, oscillation and three speeds. Full height, for a room, not a desk.",
    price: 28500,
    images: ["/products/stand-fan.jpg"],
    specs: { Size: "18 inch", Speeds: "3", Type: "Pedestal", Oscillation: "Yes" },
    colors: [{ name: "Black", hex: "#1A1A1A" }],
    sizes: ["18 inch"],
    dimensions: "Height about 125 cm",
    material: "ABS and steel stand",
    stock: 22,
    warranty: w12,
    bestseller: true,
  },
  {
    id: "breezeline-desk-fan",
    categoryId: "fans",
    name: "BreezeLine 12-inch Desk Fan",
    description: "Small oscillating desk fan, about 12 inches, with a metal grille and a cream base. It sits on a table. It is not a standing fan.",
    price: 14500,
    images: ["/products/fan.jpg"],
    specs: { Size: "12 inch", Type: "Desk", Oscillation: "Yes" },
    colors: [{ name: "Cream / chrome", hex: "#D9D3C7" }],
    sizes: ["12 inch"],
    dimensions: "Height about 40 cm",
    material: "Metal grille, plastic base",
    stock: 18,
    warranty: w12,
  },
  {
    id: "breeze-ceiling",
    categoryId: "fans",
    name: "BreezeLine Walnut Ceiling Fan",
    description: "Three-blade ceiling fan with walnut blades and a white central light. For a standard ceiling mount. Installation in Abuja can be arranged.",
    price: 65000,
    images: ["/products/ceiling-fan.jpg"],
    specs: { Blades: "3 walnut", Light: "Central", Mount: "Ceiling" },
    colors: [{ name: "Walnut / white", hex: "#8A6240" }],
    sizes: ["48 inch"],
    dimensions: "Blade span 122 cm",
    material: "Wood blades, metal motor",
    stock: 7,
    warranty: w12,
    newArrival: true,
  },
  {
    id: "millhouse-blender",
    categoryId: "other-appliances",
    name: "Millhouse Glass Jug Blender",
    description: "Countertop blender with a clear glass jug and a matte black base. For smoothies, soups and wet milling. Not a coffee grinder.",
    price: 48500,
    images: ["/products/blender-glass.jpg"],
    specs: { Jug: "1.5L glass", Speeds: "3 + pulse" },
    colors: [{ name: "Black / glass", hex: "#2A2A2A" }],
    sizes: ["1.5L"],
    dimensions: "18 × 18 × 40 cm",
    material: "Glass jug, stainless blades",
    stock: 15,
    warranty: w12,
  },
  {
    id: "copper-kettle",
    categoryId: "other-appliances",
    name: "Forge 1.7L Electric Kettle",
    description: "Electric kettle with a copper-toned steel body, black handle and base. 1.7 litres, auto shut-off and boil-dry protection.",
    price: 24500,
    images: ["/products/kettle-copper.jpg"],
    specs: { Capacity: "1.7L", Shutoff: "Auto", Protection: "Boil-dry" },
    colors: [{ name: "Copper", hex: "#B87333" }],
    sizes: ["1.7L"],
    dimensions: "22 × 16 × 24 cm",
    material: "Stainless steel",
    stock: 18,
    warranty: w12,
  },
  {
    id: "clearwell-dispenser",
    categoryId: "other-appliances",
    name: "Clearwell Bottom-Load Water Dispenser",
    description: "White water dispenser with the bottle loaded in the bottom cabinet and two front taps, hot and cold. A floor-standing dispenser, not a kettle.",
    price: 68000,
    images: ["/products/dispenser-new.jpg"],
    specs: { Load: "Bottom bottle", Taps: "Hot and cold", Type: "Floor standing" },
    colors: [{ name: "White", hex: "#F4F4F2" }],
    sizes: ["Standard bottle"],
    dimensions: "31 × 36 × 104 cm",
    material: "ABS and steel",
    stock: 8,
    warranty: w12,
    featured: true,
  },
  {
    id: "crisp-airfryer",
    categoryId: "other-appliances",
    name: "Crisp 5.5L Air Fryer",
    description: "Matte black basket air fryer, 5.5 litres, front pull-out drawer. Countertop only. Not an oven range.",
    price: 55000,
    images: ["/products/airfryer.jpg"],
    specs: { Capacity: "5.5 litres", Type: "Basket air fryer" },
    colors: [{ name: "Black", hex: "#1A1A1A" }],
    sizes: ["5.5L"],
    dimensions: "30 × 36 × 32 cm",
    material: "Steel and plastic",
    stock: 14,
    warranty: w12,
    specialOffer: true,
    newArrival: true,
  },
  {
    id: "hearth-toaster-oven",
    categoryId: "other-appliances",
    name: "Hearth Countertop Toaster Oven",
    description: "Stainless countertop toaster oven with a glass door and three control knobs. For toast, bake and grill on a worktop. Not a full-size cooker.",
    price: 42000,
    images: ["/products/toaster-oven.jpg"],
    specs: { Type: "Countertop toaster oven", Controls: "3 knobs" },
    colors: [{ name: "Stainless", hex: "#C5C7C4" }],
    sizes: ["20L class"],
    dimensions: "45 × 36 × 26 cm",
    material: "Stainless steel, glass door",
    stock: 10,
    warranty: w12,
  },
  {
    id: "helios-55",
    categoryId: "televisions",
    name: "Helios 55\" 4K Smart TV",
    description: "55-inch 4K smart television with a thin black bezel, shown on a low oak stand. HDR, dual-band Wi-Fi, three HDMI. The stand in the photograph is not included.",
    price: 485000,
    compareAt: 545000,
    images: ["/products/tv-55-clean.jpg"],
    specs: { Size: "55 inch", Resolution: "4K UHD", HDR: "Yes", HDMI: "3" },
    colors: [{ name: "Black", hex: "#111111" }],
    sizes: ["55\""],
    dimensions: "123 × 71 × 8 cm without stand",
    material: "Plastic bezel, metal stand feet included",
    stock: 7,
    warranty: w24,
    featured: true,
    bestseller: true,
    specialOffer: true,
  },
  {
    id: "crestline-43",
    categoryId: "televisions",
    name: "Crestline 43\" Full HD Smart TV",
    description: "43-inch Full HD smart television for a bedroom or compact room. Thinner than the 55 and 65. HDMI and USB. The dresser in the photograph is not included.",
    price: 245000,
    compareAt: 285000,
    images: ["/products/tv-43-clean.jpg"],
    specs: { Size: "43 inch", Resolution: "Full HD", HDMI: "2" },
    colors: [{ name: "Black", hex: "#111111" }],
    sizes: ["43\""],
    dimensions: "96 × 56 × 8 cm",
    material: "Plastic bezel",
    stock: 9,
    warranty: w12,
    specialOffer: true,
  },
  {
    id: "helios-65",
    categoryId: "televisions",
    name: "Helios 65\" 4K Smart TV",
    description: "65-inch 4K smart television with an ultra-thin bezel, meant for wall mounting. The soundbar in the room photograph is sold separately as the Nile system, or together in the cinema set.",
    price: 720000,
    images: ["/products/tv-65.jpg"],
    specs: { Size: "65 inch", Resolution: "4K UHD", HDR: "Yes", Mount: "Wall-mount ready" },
    colors: [{ name: "Black", hex: "#111111" }],
    sizes: ["65\""],
    dimensions: "145 × 84 × 6 cm without stand",
    material: "Metal and plastic",
    stock: 4,
    warranty: w24,
    featured: true,
    newArrival: true,
  },
  {
    id: "theatre-51",
    categoryId: "sound-systems",
    name: "Nile 2.1 Soundbar",
    description: "Long black soundbar with a separate wireless subwoofer cube. HDMI ARC and Bluetooth. A sound system, not a television.",
    price: 185000,
    images: ["/products/soundbar-sub.jpg"],
    specs: { Channels: "2.1", Sub: "Wireless cube", HDMI: "ARC" },
    colors: [{ name: "Black", hex: "#111111" }],
    sizes: ["2.1"],
    dimensions: "Bar 90 cm; sub about 20 cm",
    material: "ABS, fabric grille",
    stock: 6,
    warranty: w12,
    bestseller: true,
  },
  {
    id: "grove-bookshelf",
    categoryId: "sound-systems",
    name: "Grove Bookshelf Speakers — Pair",
    description: "Matched pair of walnut bookshelf speakers with black fabric grilles. Passive speakers for a shelf beside a television. Sold as a pair. Amplifier not included.",
    price: 125000,
    images: ["/products/bookshelf-spk.jpg"],
    specs: { Pack: "2 speakers", Type: "Passive bookshelf", Grille: "Black fabric" },
    colors: [{ name: "Walnut", hex: "#6B4226" }],
    sizes: ["Pair"],
    dimensions: "Each 18 × 22 × 30 cm",
    material: "Wood cabinet, fabric grille",
    stock: 5,
    warranty: w12,
    newArrival: true,
  },
  {
    id: "pulse-speaker",
    categoryId: "speakers",
    name: "Pulse Portable Speaker",
    description: "Portable Bluetooth speaker in black woven fabric with rubber end caps. About 12 hours of battery and IPX5 splash resistance. A single speaker, not a home-theatre pair.",
    price: 42000,
    images: ["/products/speaker-bt.jpg"],
    specs: { Battery: "12 hours", Waterproof: "IPX5", Connectivity: "Bluetooth 5.3" },
    colors: [{ name: "Black", hex: "#1A1A1A" }],
    sizes: ["Single"],
    dimensions: "20 × 8 × 8 cm",
    material: "Fabric, rubber",
    stock: 20,
    warranty: w12,
    bestseller: true,
  },
  {
    id: "cinema-bundle",
    categoryId: "home-entertainment",
    name: "65\" Television and Soundbar Set",
    description: "One delivery: the Helios 65-inch 4K TV and the Nile 2.1 soundbar with subwoofer. Wall placement in Abuja is included when you book it. The oak shelf in the photograph is not part of the set.",
    price: 860000,
    compareAt: 905000,
    images: ["/products/tv-65.jpg", "/products/soundbar-sub.jpg"],
    specs: { Includes: "65\" 4K TV + 2.1 soundbar and sub", Setup: "In-Abuja wall placement on request" },
    colors: [{ name: "Black", hex: "#111111" }],
    sizes: ["65\" set"],
    dimensions: "TV 65 inch; bar 90 cm",
    material: "Mixed",
    stock: 3,
    warranty: w24,
    featured: true,
    specialOffer: true,
  },
  {
    id: "studio-cans",
    categoryId: "accessories",
    name: "Studio Wireless Headphones",
    description: "Black over-ear wireless headphones with leatherette cushions. About 30 hours of battery. An accessory, not a speaker.",
    price: 38500,
    images: ["/products/headphones-bk.jpg"],
    specs: { Battery: "30 hours", Type: "Over-ear", Connectivity: "Bluetooth" },
    colors: [{ name: "Black", hex: "#1A1A1A" }],
    sizes: ["Standard"],
    dimensions: "Foldable",
    material: "Leatherette, plastic",
    stock: 16,
    warranty: w12,
  },
  {
    id: "hdmi-kit",
    categoryId: "accessories",
    name: "TV Connection Kit",
    description: "Two HDMI cables, a three-socket surge protector, and a black TV wall-mount bracket. The kit we send with most television sales. No television included.",
    price: 18500,
    images: ["/products/hdmi-kit.jpg"],
    specs: { Includes: "2× HDMI, surge strip, wall-mount bracket" },
    colors: [{ name: "Black", hex: "#1A1A1A" }],
    sizes: ["Kit"],
    dimensions: "Boxed",
    material: "Mixed",
    stock: 30,
    warranty: "6 months on accessories.",
  },
  {
    id: "stream-puck",
    categoryId: "other-electronics",
    name: "Stream 4K Media Puck",
    description: "Small matte-black streaming puck with an HDMI lead. Plugs into a television for apps when the set itself is not smart enough. Not a speaker and not a television.",
    price: 28000,
    images: ["/products/streamer.jpg"],
    specs: { Output: "4K HDR via HDMI", Connection: "Wi-Fi", Power: "USB" },
    colors: [{ name: "Black", hex: "#1A1A1A" }],
    sizes: ["Single"],
    dimensions: "About 10 cm across",
    material: "Plastic",
    stock: 20,
    warranty: w12,
    newArrival: true,
  },
  {
    id: "maitama-power-sofa",
    categoryId: "sofas",
    name: "Charcoal Power Recliner Sofa",
    description: "Three-seater in charcoal leather. The two end seats recline and their footrests come forward; the centre seat stays upright. Block arms and dark walnut feet. A sofa, not a chair.",
    price: 780000,
    compareAt: 860000,
    images: ["/products/sofa-recliner.jpg"],
    specs: { Seating: "3-seater", Recline: "Both ends, centre fixed", Feet: "Walnut block" },
    colors: [{ name: "Charcoal leather", hex: "#2C2C2C" }],
    sizes: ["3-seater"],
    dimensions: "228 × 98 × 102 cm",
    material: "Leather, hardwood, steel recline mechanism",
    stock: 3,
    warranty: wFrame,
    featured: true,
    newArrival: true,
    specialOffer: true,
  },
  {
    id: "garki-storage-bed",
    categoryId: "beds",
    name: "Walnut Storage King Bed",
    description: "King bed in walnut with a flat panel headboard and four storage drawers in the base — two on each long side. Shown dressed in ivory linen. The mattress and linen in the photograph are not included.",
    price: 395000,
    images: ["/products/bed-storage.jpg"],
    specs: { Size: "King 6×6", Drawers: "4, two per side", Headboard: "Flat walnut panel" },
    colors: [{ name: "Walnut", hex: "#5C4033" }],
    sizes: ["6×6 King"],
    dimensions: "210 × 195 × 110 cm",
    material: "Walnut veneer, solid wood rails",
    stock: 3,
    warranty: "5-year structural warranty.",
    featured: true,
    newArrival: true,
  },
  {
    id: "hybridrest-king",
    categoryId: "mattresses",
    name: "HybridRest Coil Mattress — King",
    description: "King mattress with a diamond-quilted ivory top, a foam comfort layer, and pocket coils visible along the side. The low oak platform in the photograph is not included.",
    price: 275000,
    images: ["/products/mattress-hybrid.jpg"],
    specs: { Profile: "About 12 inch", Feel: "Medium", Core: "Pocket coil under foam", Cover: "Diamond quilt" },
    colors: [{ name: "Ivory", hex: "#F3EEE6" }],
    sizes: ["6×6 King"],
    dimensions: "200 × 180 × 30 cm",
    material: "Pocket coils, foam, quilted cover",
    stock: 6,
    warranty: "10-year limited mattress warranty.",
    featured: true,
    newArrival: true,
  },
  {
    id: "round-oak-dining",
    categoryId: "dining-sets",
    name: "Round Oak 4-Seater Dining Set",
    description: "Round light-oak table on a solid pedestal, sold with exactly four greige upholstered chairs on oak legs. A dining set, not extra chairs on their own.",
    price: 295000,
    images: ["/products/dining-round.jpg"],
    specs: { Seats: "4", Table: "Round oak pedestal", Chairs: "Greige upholstered" },
    colors: [{ name: "Oak / greige", hex: "#D8CBB8" }],
    sizes: ["4-seater round"],
    dimensions: "Table diameter 120 cm, height 76 cm",
    material: "Oak, fabric chairs",
    stock: 4,
    warranty: w24,
    newArrival: true,
    featured: true,
  },
  {
    id: "nest-centre-tables",
    categoryId: "tables",
    name: "Oak Nesting Coffee Tables",
    description: "A pair of rectangular oak coffee tables with black hairpin legs. The smaller top is sized to slide under the larger one. Sold as the pair. Not dining tables.",
    price: 88000,
    images: ["/products/tables-nest.jpg"],
    specs: { Pack: "2 tables", Legs: "Black hairpin", Use: "Coffee / centre" },
    colors: [{ name: "Oak / black", hex: "#C4A574" }],
    sizes: ["Pair"],
    dimensions: "Large 90 × 50 × 45 cm; small 70 × 40 × 38 cm",
    material: "Oak tops, steel legs",
    stock: 8,
    warranty: w12,
    newArrival: true,
  },
  {
    id: "cognac-lounge-set",
    categoryId: "chairs",
    name: "Cognac Leather Chair and Ottoman",
    description: "One lounge chair and one matching ottoman in cognac leather, both on dark walnut legs. Sold together. Not a dining chair and not a sofa.",
    price: 245000,
    images: ["/products/chair-ottoman.jpg"],
    specs: { Includes: "Chair and ottoman", Leather: "Cognac", Legs: "Walnut" },
    colors: [{ name: "Cognac", hex: "#A15C2E" }],
    sizes: ["Chair + ottoman"],
    dimensions: "Chair 82 × 90 × 80 cm",
    material: "Leather, walnut",
    stock: 4,
    warranty: wFrame,
    featured: true,
    newArrival: true,
  },
  {
    id: "floor-media-console",
    categoryId: "tv-stands",
    name: "Walnut Floor Media Console",
    description: "Floor-standing walnut console on short legs. Two cupboard doors on the left, an open centre with one shelf, and two drawers on the right. It sits on the floor — it is not the wall-mounted smoked oak unit. No television included.",
    price: 175000,
    images: ["/products/tv-console-floor.jpg"],
    specs: { Mount: "Floor standing", Storage: "2 doors, open shelf, 2 drawers", Television: "Not included" },
    colors: [{ name: "Walnut", hex: "#5C4033" }],
    sizes: ["180 cm"],
    dimensions: "180 × 42 × 55 cm",
    material: "Walnut veneer, engineered wood",
    stock: 5,
    warranty: w12,
    newArrival: true,
    featured: true,
  },
  {
    id: "glass-vitrine",
    categoryId: "cabinets",
    name: "Walnut Glass Display Cabinet",
    description: "Tall walnut cabinet. The upper half has two glass doors and open shelves; the lower half has two solid doors. Brass knobs. The bowls in the photograph are not included. Not a wardrobe and not a sideboard.",
    price: 265000,
    images: ["/products/cabinet-vitrine.jpg"],
    specs: { Upper: "2 glass doors", Lower: "2 solid doors", Hardware: "Brass knobs" },
    colors: [{ name: "Walnut", hex: "#5C4033" }],
    sizes: ["90 cm wide"],
    dimensions: "90 × 42 × 190 cm",
    material: "Walnut veneer, glass",
    stock: 3,
    warranty: w12,
    newArrival: true,
  },
  {
    id: "lift-standing-desk",
    categoryId: "office-furniture",
    name: "Lift Oak Standing Desk",
    description: "Height-adjustable desk with a pale oak top, a black electric column on each side, and a black desk mat. Shown at a mid rise. Chair, laptop and monitor are not included.",
    price: 245000,
    images: ["/products/desk-standing.jpg"],
    specs: { Lift: "Electric, two columns", Top: "Oak", Includes: "Desk and mat" },
    colors: [{ name: "Oak / black", hex: "#C4A574" }],
    sizes: ["140 cm"],
    dimensions: "140 × 70 cm top",
    material: "Oak top, steel legs",
    stock: 4,
    warranty: w24,
    featured: true,
    newArrival: true,
  },
  {
    id: "brass-sconce-pair",
    categoryId: "lighting",
    name: "Brass Wall Sconces — Pair",
    description: "Two matching wall lights. Each has a round brass backplate, a curved arm and an ivory linen drum shade. Sold as the pair. Hardwired. Not a floor lamp and not a table lamp.",
    price: 92000,
    images: ["/products/sconce-pair.jpg"],
    specs: { Pack: "2 sconces", Shade: "Linen drum", Fitting: "Hardwired" },
    colors: [{ name: "Brass / ivory", hex: "#C4B08A" }],
    sizes: ["Pair"],
    dimensions: "Each about 22 cm wide",
    material: "Brass-finished metal, linen",
    stock: 6,
    warranty: w12,
    newArrival: true,
  },
  {
    id: "frostpeak-sbs",
    categoryId: "refrigerators",
    name: "FrostPeak Side-by-Side Refrigerator",
    description: "Stainless side-by-side refrigerator. Two full-height doors, with a water and ice dispenser on the left door. It is not the top-freezer double-door and not the French-door model.",
    price: 890000,
    images: ["/products/fridge-sbs.jpg"],
    specs: { Layout: "Side-by-side", Dispenser: "Water and ice, left door", Finish: "Stainless" },
    colors: [{ name: "Stainless", hex: "#C5C7C4" }],
    sizes: ["Family"],
    dimensions: "91 × 75 × 178 cm",
    material: "Steel cabinet",
    stock: 2,
    warranty: w24,
    featured: true,
    newArrival: true,
  },
  {
    id: "chillvault-wide",
    categoryId: "freezers",
    name: "ChillVault Wide Chest Freezer",
    description: "Wide white chest freezer with the lid closed, a front lock and a control panel on the lower right. A freezer only — it is not an upright fridge.",
    price: 320000,
    images: ["/products/freezer-wide.jpg"],
    specs: { Type: "Chest", Lid: "Top, closed", Lock: "Front" },
    colors: [{ name: "White", hex: "#F4F4F2" }],
    sizes: ["Wide"],
    dimensions: "130 × 70 × 85 cm",
    material: "Steel cabinet",
    stock: 4,
    warranty: w24,
    newArrival: true,
  },
  {
    id: "aquacycle-stack",
    categoryId: "washing-machines",
    name: "AquaCycle Washer and Dryer Stack",
    description: "A white front-loading washer on the floor with a matching dryer stacked on top of it. Both have round glass doors. Sold as the pair with the stacking kit. Not a single top-loader.",
    price: 690000,
    compareAt: 760000,
    images: ["/products/washer-stack.jpg"],
    specs: { Includes: "Front-load washer, dryer, stacking kit", Doors: "Round glass, both" },
    colors: [{ name: "White", hex: "#F4F4F2" }],
    sizes: ["Stack"],
    dimensions: "Footprint 60 × 65 cm, stacked height about 170 cm",
    material: "Steel, glass doors",
    stock: 3,
    warranty: w24,
    featured: true,
    newArrival: true,
    specialOffer: true,
  },
  {
    id: "flamehaus-six",
    categoryId: "cookers",
    name: "FlameHaus 6-Burner Gas Range",
    description: "Wide freestanding stainless range. Six gas burners in two rows of three, cast-iron grates, and one oven with a glass door. No hinged glass lid. It is larger than the 4-burner cooker.",
    price: 385000,
    images: ["/products/range-six.jpg"],
    specs: { Burners: "6 gas", Oven: "1", Fuel: "LPG", Type: "Freestanding range" },
    colors: [{ name: "Stainless", hex: "#C5C7C4" }],
    sizes: ["90 cm"],
    dimensions: "90 × 60 × 90 cm",
    material: "Stainless steel, enamel oven",
    stock: 3,
    warranty: w12,
    newArrival: true,
    featured: true,
  },
  {
    id: "breezeline-tower",
    categoryId: "fans",
    name: "BreezeLine Tower Fan",
    description: "Slim black tower fan with a round base and a column grille. No exposed blades. It stands on the floor. It is not the pedestal fan and not the desk fan.",
    price: 42000,
    images: ["/products/fan-tower.jpg"],
    specs: { Type: "Tower", Blades: "Hidden in the column", Base: "Round" },
    colors: [{ name: "Black", hex: "#1A1A1A" }],
    sizes: ["Tower"],
    dimensions: "Height about 105 cm",
    material: "ABS",
    stock: 12,
    warranty: w12,
    newArrival: true,
  },
  {
    id: "breezeline-black",
    categoryId: "air-conditioners",
    name: "BreezeLine Black Split Air Conditioner",
    description: "Matte black wall-mounted indoor unit with a white remote. The outdoor condenser is supplied with the set and is not in the photograph. Not a fan.",
    price: 345000,
    images: ["/products/ac-black.jpg"],
    specs: { Type: "Split, wall indoor unit", Finish: "Matte black", Includes: "Indoor unit, outdoor unit, remote" },
    colors: [{ name: "Matte black", hex: "#1A1A1A" }],
    sizes: ["1.5 HP", "2 HP"],
    dimensions: "Indoor about 90 × 22 × 30 cm",
    material: "ABS indoor, copper coil",
    stock: 4,
    warranty: w24,
    newArrival: true,
  },
  {
    id: "forge-espresso",
    categoryId: "other-appliances",
    name: "Forge Espresso Machine",
    description: "Compact stainless espresso machine with a pressure gauge, portafilter, steam wand and a stainless milk jug. The jug is included. A countertop coffee machine, not a kettle.",
    price: 165000,
    images: ["/products/espresso.jpg"],
    specs: { Type: "Espresso", Includes: "Machine and milk jug", Steam: "Yes" },
    colors: [{ name: "Stainless", hex: "#C5C7C4" }],
    sizes: ["Compact"],
    dimensions: "28 × 32 × 32 cm",
    material: "Stainless steel",
    stock: 6,
    warranty: w12,
    newArrival: true,
    featured: true,
  },
  {
    id: "clearwell-dishwasher",
    categoryId: "other-appliances",
    name: "Clearwell Freestanding Dishwasher",
    description: "White freestanding dishwasher with the door closed, a long handle and controls along the top edge. It washes dishes. It is not a washing machine.",
    price: 285000,
    images: ["/products/dishwasher.jpg"],
    specs: { Type: "Freestanding dishwasher", Door: "Closed, top controls" },
    colors: [{ name: "White", hex: "#F4F4F2" }],
    sizes: ["60 cm"],
    dimensions: "60 × 60 × 85 cm",
    material: "Steel cabinet",
    stock: 4,
    warranty: w24,
    newArrival: true,
  },
  {
    id: "sweep-robot",
    categoryId: "other-appliances",
    name: "Sweep Robot Vacuum",
    description: "Round white robot vacuum with a top sensor, a front bumper and side brushes. It runs on the floor. Not an upright vacuum and not a fan.",
    price: 145000,
    images: ["/products/robot-vacuum.jpg"],
    specs: { Type: "Robot vacuum", Shape: "Round disc", Brushes: "Side" },
    colors: [{ name: "White", hex: "#F4F4F2" }],
    sizes: ["Single"],
    dimensions: "About 35 cm across",
    material: "ABS",
    stock: 8,
    warranty: w12,
    newArrival: true,
  },
  {
    id: "helios-75",
    categoryId: "televisions",
    name: "Helios 75\" 4K Smart TV",
    description: "Large 75-inch 4K smart television with a thin black bezel. The oak console in the photograph is for scale and is not included. No soundbar is in this picture — sound is a separate category.",
    price: 980000,
    images: ["/products/tv-75.jpg"],
    specs: { Size: "75 inch", Resolution: "4K UHD", Soundbar: "Not included", Console: "Not included" },
    colors: [{ name: "Black", hex: "#111111" }],
    sizes: ["75\""],
    dimensions: "167 × 96 × 6 cm without stand",
    material: "Metal and plastic",
    stock: 2,
    warranty: w24,
    featured: true,
    newArrival: true,
  },
  {
    id: "nile-satellites",
    categoryId: "sound-systems",
    name: "Nile Bar, Satellites and Sub",
    description: "One long black soundbar, two small black satellite speakers, and a black subwoofer with a front port. No television. The oak console and basket in the photograph are not included.",
    price: 265000,
    images: ["/products/sound-satellites.jpg"],
    specs: { Includes: "Soundbar, 2 satellites, subwoofer", Television: "Not included" },
    colors: [{ name: "Black", hex: "#111111" }],
    sizes: ["Set"],
    dimensions: "Bar about 90 cm",
    material: "ABS, fabric grille",
    stock: 4,
    warranty: w12,
    newArrival: true,
    featured: true,
  },
  {
    id: "pulse-party",
    categoryId: "speakers",
    name: "Pulse Party Speaker",
    description: "One tall portable speaker in black fabric with a top carry handle and wheels at the base. A single speaker you can roll. Not a soundbar and not a bookshelf pair.",
    price: 125000,
    images: ["/products/speaker-party.jpg"],
    specs: { Type: "Portable party speaker", Handle: "Top", Wheels: "Yes", Pack: "1" },
    colors: [{ name: "Black", hex: "#1A1A1A" }],
    sizes: ["Single"],
    dimensions: "About 30 × 28 × 70 cm",
    material: "Fabric grille, plastic shell",
    stock: 7,
    warranty: w12,
    newArrival: true,
    bestseller: true,
  },
  {
    id: "lumen-projector",
    categoryId: "other-electronics",
    name: "Lumen Home Projector",
    description: "Compact white projector with a front lens and a perforated side grille. An HDMI cable is included. The shelf in the photograph is not. It is not a television.",
    price: 195000,
    images: ["/products/projector.jpg"],
    specs: { Type: "Home projector", Includes: "Projector and HDMI cable", Screen: "Not included" },
    colors: [{ name: "White", hex: "#F4F4F2" }],
    sizes: ["Single"],
    dimensions: "About 22 × 18 × 10 cm",
    material: "ABS",
    stock: 5,
    warranty: w12,
    newArrival: true,
  },
  {
    id: "mesh-pair",
    categoryId: "other-electronics",
    name: "House Mesh Wi-Fi — Pair",
    description: "Two white cylindrical mesh nodes with a small status light on each. Sold as the pair for a larger flat. The table in the photograph is not included. Not a speaker.",
    price: 78000,
    images: ["/products/mesh-wifi.jpg"],
    specs: { Pack: "2 nodes", Shape: "Short cylinder" },
    colors: [{ name: "White", hex: "#F4F4F2" }],
    sizes: ["Pair"],
    dimensions: "Each about 10 cm tall",
    material: "Plastic",
    stock: 10,
    warranty: w12,
    newArrival: true,
  },
  {
    id: "wuse-curve-sofa",
    categoryId: "sofas",
    name: "Curve Bouclé Sofa",
    description: "Three-seater with one continuous rounded arm in cream bouclé, three loose back cushions and short oak legs. A curved sofa, not a sectional and not a leather piece.",
    price: 540000,
    compareAt: 620000,
    images: ["/products/sofa-curve.jpg"],
    specs: { Seating: "3-seater", Arms: "Continuous curve", Fill: "High-resilience foam", Legs: "Oak" },
    colors: [{ name: "Cream bouclé", hex: "#F3EDE3" }],
    sizes: ["3-seater"],
    dimensions: "230 × 96 × 78 cm",
    material: "Bouclé on hardwood",
    stock: 3,
    warranty: wFrame,
    featured: true,
    newArrival: true,
    specialOffer: true,
  },
  {
    id: "ivory-mirror-wardrobe",
    categoryId: "wardrobes",
    name: "Ivory Mirror Sliding Wardrobe",
    description: "Three-door sliding wardrobe in warm white. The left door is a full-length mirror; the centre and right doors are plain panels with slim black handles. Empty inside when delivered. Not a hinged wardrobe.",
    price: 385000,
    images: ["/products/wardrobe-mirror.jpg"],
    specs: { Doors: "3 sliding", Mirror: "Left door only", Handles: "Black" },
    colors: [{ name: "Warm white", hex: "#F4F0EA" }],
    sizes: ["180 cm"],
    dimensions: "180 × 62 × 210 cm",
    material: "Engineered wood, mirror glass",
    stock: 3,
    warranty: w24,
    featured: true,
    newArrival: true,
  },
  {
    id: "oak-open-wardrobe",
    categoryId: "wardrobes",
    name: "Oak Open Wardrobe",
    description: "Open oak wardrobe with no doors. Two hanging rails, wooden hangers included, a mid shelf and a lower shelf. It is not a closed wardrobe and not a bookcase.",
    price: 210000,
    images: ["/products/wardrobe-open.jpg"],
    specs: { Doors: "None", Rails: "2", Hangers: "Included" },
    colors: [{ name: "Oak", hex: "#C4A574" }],
    sizes: ["120 cm"],
    dimensions: "120 × 55 × 200 cm",
    material: "Oak veneer, solid wood rails",
    stock: 4,
    warranty: w12,
    newArrival: true,
  },
  {
    id: "oak-bedside-pair",
    categoryId: "tables",
    name: "Oak Bedside Tables — Pair",
    description: "Two matching bedside tables in oak. Each has one drawer with a round oak knob and an open shelf below. Sold as the pair. Not coffee tables and not a console.",
    price: 95000,
    images: ["/products/bedside-pair.jpg"],
    specs: { Pack: "2 tables", Drawer: "1 each", Shelf: "Open, below" },
    colors: [{ name: "Oak", hex: "#C4A574" }],
    sizes: ["Pair"],
    dimensions: "Each 45 × 38 × 55 cm",
    material: "Oak",
    stock: 8,
    warranty: w12,
    newArrival: true,
    bestseller: true,
  },
  {
    id: "oak-dining-eight",
    categoryId: "dining-sets",
    name: "Oak 8-Seater Dining Set",
    description: "Long light-oak rectangular table sold with exactly eight greige upholstered chairs, four along each long side. The vase and bowl in the photograph are not included. A dining set, not loose chairs.",
    price: 620000,
    compareAt: 690000,
    images: ["/products/dining-8.jpg"],
    specs: { Seats: "8", Table: "Rectangular oak", Chairs: "Greige upholstered" },
    colors: [{ name: "Oak / greige", hex: "#D8CBB8" }],
    sizes: ["8-seater"],
    dimensions: "Table 220 × 95 × 76 cm",
    material: "Oak, fabric chairs",
    stock: 2,
    warranty: w24,
    featured: true,
    newArrival: true,
    specialOffer: true,
  },
  {
    id: "jabi-bookcase",
    categoryId: "office-furniture",
    name: "Oak Open Bookcase",
    description: "Tall narrow oak bookcase with five open shelves. A few ceramic pieces are shown for scale and are not included. A bookcase, not a wardrobe and not a desk.",
    price: 145000,
    images: ["/products/bookshelf.jpg"],
    specs: { Shelves: "5 open", Doors: "None" },
    colors: [{ name: "Oak", hex: "#C4A574" }],
    sizes: ["80 cm"],
    dimensions: "80 × 35 × 200 cm",
    material: "Oak veneer",
    stock: 5,
    warranty: w12,
    newArrival: true,
    featured: true,
  },
  {
    id: "linen-drum-pendant",
    categoryId: "lighting",
    name: "Linen Drum Pendant",
    description: "One large ivory linen drum shade on a thin cord. Hardwired. The dining table in the photograph is not included. Not a cluster pendant and not a floor lamp.",
    price: 78000,
    images: ["/products/pendant-drum.jpg"],
    specs: { Shade: "Linen drum", Fitting: "Hardwired", Pack: "1" },
    colors: [{ name: "Ivory linen", hex: "#EFE6D8" }],
    sizes: ["60 cm shade"],
    dimensions: "Shade about 60 cm across",
    material: "Linen, metal fitting",
    stock: 7,
    warranty: w12,
    newArrival: true,
  },
  {
    id: "frostpeak-black",
    categoryId: "refrigerators",
    name: "FrostPeak Black Double-Door Refrigerator",
    description: "Matte black top-freezer refrigerator. A smaller freezer door sits above a larger fridge door, each with a vertical handle. It is not the stainless double-door, not the French-door, and not a side-by-side.",
    price: 410000,
    images: ["/products/fridge-black.jpg"],
    specs: { Layout: "Top freezer, two doors", Finish: "Matte black", Freezer: "Upper door" },
    colors: [{ name: "Matte black", hex: "#1A1A1A" }],
    sizes: ["Family"],
    dimensions: "70 × 70 × 175 cm",
    material: "Steel cabinet",
    stock: 3,
    warranty: w24,
    featured: true,
    newArrival: true,
  },
  {
    id: "chillvault-slim",
    categoryId: "freezers",
    name: "ChillVault Slim Upright Freezer",
    description: "Narrow white upright freezer with a single solid door and one vertical handle. No second door and no fridge compartment. It is not a refrigerator.",
    price: 275000,
    images: ["/products/freezer-slim.jpg"],
    specs: { Type: "Upright freezer", Doors: "1 solid", Fridge: "None" },
    colors: [{ name: "White", hex: "#F4F4F2" }],
    sizes: ["Slim"],
    dimensions: "55 × 60 × 145 cm",
    material: "Steel cabinet",
    stock: 4,
    warranty: w24,
    newArrival: true,
  },
  {
    id: "aquacycle-combo",
    categoryId: "washing-machines",
    name: "AquaCycle Washer-Dryer Combo",
    description: "One white front-loading machine that both washes and dries. A single round glass door, a taller control panel, and a lower service panel. It is one appliance, not a stacked washer and dryer.",
    price: 520000,
    compareAt: 575000,
    images: ["/products/washer-combo.jpg"],
    specs: { Type: "Washer-dryer combo", Doors: "1 round glass", Machines: "1" },
    colors: [{ name: "White", hex: "#F4F4F2" }],
    sizes: ["8 kg wash"],
    dimensions: "60 × 60 × 85 cm",
    material: "Steel, glass door",
    stock: 3,
    warranty: w24,
    featured: true,
    newArrival: true,
    specialOffer: true,
  },
  {
    id: "flamehaus-five",
    categoryId: "cookers",
    name: "FlameHaus 5-Burner Gas Cooker",
    description: "Freestanding stainless gas cooker with five burners, cast-iron grates, a glass lid and one oven. Wider than the 4-burner and narrower than the 6-burner range. LPG. It stands on the floor.",
    price: 245000,
    images: ["/products/cooker-five.jpg"],
    specs: { Burners: "5 gas", Oven: "Yes", Fuel: "LPG", Type: "Freestanding" },
    colors: [{ name: "Stainless", hex: "#C5C7C4" }],
    sizes: ["60 cm"],
    dimensions: "60 × 60 × 90 cm",
    material: "Stainless steel, enamel oven",
    stock: 4,
    warranty: w12,
    newArrival: true,
    bestseller: true,
  },
  {
    id: "heatwave-white",
    categoryId: "microwaves",
    name: "HeatWave 20L White Microwave",
    description: "White countertop microwave, about 20 litres, with a black glass door and one dial on the right. It sits on a worktop. It is not the black grill microwave.",
    price: 48000,
    images: ["/products/microwave-white.jpg"],
    specs: { Capacity: "20 litres", Controls: "Dial", Type: "Countertop", Colour: "White" },
    colors: [{ name: "White", hex: "#F4F4F2" }],
    sizes: ["20L"],
    dimensions: "44 × 34 × 26 cm",
    material: "Steel cavity, glass door",
    stock: 14,
    warranty: w12,
    newArrival: true,
    specialOffer: true,
  },
  {
    id: "millhouse-rice",
    categoryId: "other-appliances",
    name: "Millhouse Rice Cooker",
    description: "White electric rice cooker with a glass lid and a front switch. For rice on the counter. Not a kettle and not a blender.",
    price: 32000,
    images: ["/products/rice-cooker.jpg"],
    specs: { Type: "Rice cooker", Lid: "Glass", Capacity: "1.8L" },
    colors: [{ name: "White", hex: "#F4F4F2" }],
    sizes: ["1.8L"],
    dimensions: "28 × 28 × 26 cm",
    material: "ABS, glass lid",
    stock: 16,
    warranty: w12,
    newArrival: true,
    bestseller: true,
  },
  {
    id: "forge-iron",
    categoryId: "other-appliances",
    name: "Forge Steam Iron",
    description: "Stainless steam iron with a black handle and cord. The board in the photograph is not included. A clothes iron, not a cooker.",
    price: 18500,
    images: ["/products/steam-iron.jpg"],
    specs: { Type: "Steam iron", Soleplate: "Stainless", Board: "Not included" },
    colors: [{ name: "Stainless / black", hex: "#C5C7C4" }],
    sizes: ["Standard"],
    dimensions: "About 30 cm long",
    material: "Stainless steel, plastic handle",
    stock: 20,
    warranty: w12,
    newArrival: true,
  },
  {
    id: "crestline-32",
    categoryId: "televisions",
    name: "Crestline 32\" HD Smart TV",
    description: "32-inch HD smart television for a bedroom or kitchen. Thin black bezel, shown on a white dresser that is not included. Smaller than the 43. Sound is sold separately.",
    price: 165000,
    images: ["/products/tv-32.jpg"],
    specs: { Size: "32 inch", Resolution: "HD", HDMI: "2", Soundbar: "Not included" },
    colors: [{ name: "Black", hex: "#111111" }],
    sizes: ["32\""],
    dimensions: "73 × 43 × 8 cm without stand",
    material: "Plastic bezel",
    stock: 10,
    warranty: w12,
    newArrival: true,
    specialOffer: true,
  },
  {
    id: "nile-slim-bar",
    categoryId: "sound-systems",
    name: "Nile Slim Soundbar",
    description: "One slim black soundbar with a fabric grille. No subwoofer and no satellites in the box. The oak console in the photograph is not included. A soundbar, not a television.",
    price: 95000,
    images: ["/products/soundbar-solo.jpg"],
    specs: { Channels: "2.0", Sub: "Not included", HDMI: "ARC" },
    colors: [{ name: "Black", hex: "#111111" }],
    sizes: ["Slim"],
    dimensions: "Bar about 80 cm",
    material: "ABS, fabric grille",
    stock: 8,
    warranty: w12,
    newArrival: true,
    featured: true,
  },
  {
    id: "grove-floor",
    categoryId: "sound-systems",
    name: "Grove Floor Speakers — Pair",
    description: "Matched pair of tall walnut floor-standing speakers with black fabric grilles. Passive. Sold as the pair. Amplifier not included. Not portable speakers and not a soundbar.",
    price: 285000,
    images: ["/products/speakers-floor.jpg"],
    specs: { Pack: "2 speakers", Type: "Passive floor-standing", Height: "About 100 cm" },
    colors: [{ name: "Walnut", hex: "#6B4226" }],
    sizes: ["Pair"],
    dimensions: "Each about 22 × 28 × 100 cm",
    material: "Wood cabinet, fabric grille",
    stock: 3,
    warranty: w12,
    newArrival: true,
    featured: true,
  },
  {
    id: "cinema-55-set",
    categoryId: "home-entertainment",
    name: "55\" Television and Soundbar Set",
    description: "One delivery: a 55-inch 4K smart television and the Nile slim soundbar, placed together. The oak console, sofa and ceramics in the photograph are not part of the set. This is the pair, not the television alone.",
    price: 560000,
    compareAt: 620000,
    images: ["/products/cinema-55.jpg", "/products/soundbar-solo.jpg"],
    specs: { Includes: "55\" 4K TV + slim soundbar", Subwoofer: "Not included", Console: "Not included" },
    colors: [{ name: "Black", hex: "#111111" }],
    sizes: ["55\" set"],
    dimensions: "TV 55 inch; bar about 80 cm",
    material: "Mixed",
    stock: 4,
    warranty: w24,
    featured: true,
    newArrival: true,
    specialOffer: true,
  },
  {
    id: "articulate-mount",
    categoryId: "accessories",
    name: "Articulating TV Wall Mount",
    description: "Black steel wall mount with an extending arm, a wall plate and a television plate. For sets from 32 to 65 inches. No television included. Hardware for a solid wall is in the box.",
    price: 22000,
    images: ["/products/wall-mount.jpg"],
    specs: { Fit: "32–65 inch", Movement: "Articulating arm", Television: "Not included" },
    colors: [{ name: "Black", hex: "#1A1A1A" }],
    sizes: ["32–65\""],
    dimensions: "Boxed",
    material: "Steel",
    stock: 24,
    warranty: "6 months on accessories.",
    newArrival: true,
  },
  {
    id: "studio-buds",
    categoryId: "accessories",
    name: "Studio Wireless Earbuds",
    description: "Matte black wireless earbuds in an open charging case. An accessory you wear, not over-ear headphones and not a speaker.",
    price: 28000,
    images: ["/products/earbuds.jpg"],
    specs: { Type: "In-ear", Case: "Charging case included", Connectivity: "Bluetooth" },
    colors: [{ name: "Black", hex: "#1A1A1A" }],
    sizes: ["Single pair"],
    dimensions: "Case about 6 cm",
    material: "Plastic",
    stock: 22,
    warranty: w12,
    newArrival: true,
    bestseller: true,
  },
  {
    id: "gwarinpa-chenille-set",
    categoryId: "sofas",
    name: "Sand Chenille 3+2+1 Sofa Set",
    description: "The sitting-room set most homes in Abuja actually order: a sand chenille three-seater, a matching two-seater and one armchair, all with track arms and oak legs. Sold as the three pieces together. The plant, side table and vase in the photograph are not included.",
    price: 685000,
    compareAt: 760000,
    images: ["/products/set-chenille-321.jpg"],
    specs: { Configuration: "3+2+1", Fabric: "Chenille", Legs: "Oak", Frame: "Kiln-dried hardwood" },
    colors: [{ name: "Sand chenille", hex: "#D9CDB8" }],
    sizes: ["3+2+1"],
    dimensions: "3-seater 220 cm, 2-seater 160 cm, chair 90 cm",
    material: "Chenille on hardwood",
    stock: 5,
    warranty: wFrame,
    featured: true,
    bestseller: true,
    specialOffer: true,
  },
  {
    id: "lugbe-leather-set",
    categoryId: "sofas",
    name: "Black Leather 3+2+1 Sofa Set",
    description: "Black top-grain leather sitting-room set: three-seater, two-seater and a single armchair with block arms and dark wood feet. The configuration Nigerian showrooms sell as a complete parlour. Sold as the set.",
    price: 1150000,
    compareAt: 1280000,
    images: ["/products/set-leather-321.jpg"],
    specs: { Configuration: "3+2+1", Leather: "Top grain", Feet: "Dark wood" },
    colors: [{ name: "Black leather", hex: "#1C1C1C" }],
    sizes: ["3+2+1"],
    dimensions: "3-seater 230 cm, 2-seater 168 cm, chair 96 cm",
    material: "Top-grain leather, hardwood",
    stock: 3,
    warranty: wFrame,
    featured: true,
    bestseller: true,
    specialOffer: true,
  },
  {
    id: "maitama-chesterfield",
    categoryId: "sofas",
    name: "Cognac Chesterfield Sofa",
    description: "Classic deep-button Chesterfield in cognac leather. Rolled arms, diamond tufting and dark turned legs. One three-seater, not a 3+2+1 set.",
    price: 545000,
    images: ["/products/sofa-chesterfield.jpg"],
    specs: { Seating: "3-seater", Style: "Chesterfield, button tufted", Leather: "Cognac" },
    colors: [{ name: "Cognac leather", hex: "#8A4B24" }],
    sizes: ["3-seater"],
    dimensions: "220 × 96 × 78 cm",
    material: "Leather, hardwood frame",
    stock: 4,
    warranty: wFrame,
    featured: true,
    newArrival: true,
  },
  {
    id: "jikwoyi-corner",
    categoryId: "sofas",
    name: "Grey Fabric Corner Sofa",
    description: "L-shaped seven-seater in warm grey woven fabric, left-hand chaise, loose back cushions and oak legs. One corner piece, so you do not need a separate loveseat.",
    price: 820000,
    images: ["/products/sofa-corner-grey.jpg"],
    specs: { Layout: "L-shape, left chaise", Seating: "6–7", Fabric: "Woven grey" },
    colors: [{ name: "Warm grey", hex: "#B7B1A8" }],
    sizes: ["Left chaise"],
    dimensions: "280 × 180 × 86 cm",
    material: "Woven fabric, hardwood",
    stock: 3,
    warranty: wFrame,
    bestseller: true,
    newArrival: true,
  },
  {
    id: "asokoro-velvet-set",
    categoryId: "sofas",
    name: "Burgundy Velvet 3+2+1 Set",
    description: "High-back sitting-room set in burgundy velvet with slim brass legs: a wide sofa, a two-seater and a wing chair. Channelled backs, not a Chesterfield. Sold as the three pieces. A formal parlour set without the carved gilt frame.",
    price: 980000,
    compareAt: 1120000,
    images: ["/products/set-velvet-royal.jpg"],
    specs: { Configuration: "Sofa, 2-seater and wing chair", Fabric: "Velvet", Legs: "Brass" },
    colors: [{ name: "Burgundy velvet", hex: "#6E1E33" }],
    sizes: ["3-piece set"],
    dimensions: "Sofa 190 cm, loveseat 145 cm, chair 82 cm",
    material: "Cotton velvet, brass legs",
    stock: 3,
    warranty: wFrame,
    featured: true,
    specialOffer: true,
  },
  {
    id: "karu-sofa-bed",
    categoryId: "sofas",
    name: "Grey Linen Sofa Bed",
    description: "Grey linen three-seater that pulls out into a guest bed. Shown closed, with the mattress edge visible under the seat. Oak legs.",
    price: 340000,
    images: ["/products/sofa-bed-grey.jpg"],
    specs: { Seating: "3-seater", Sleeps: "Guest bed when opened", Mechanism: "Pull-out" },
    colors: [{ name: "Grey linen", hex: "#C5C1B8" }],
    sizes: ["3-seater / guest bed"],
    dimensions: "210 × 96 × 86 cm closed",
    material: "Linen blend, hardwood",
    stock: 4,
    warranty: wFrame,
    newArrival: true,
  },
  {
    id: "wuse-cloud-modular",
    categoryId: "sofas",
    name: "Oatmeal Modular Sofa",
    description: "Low, deep modular in oatmeal bouclé. Four modules make a generous L with no tall arms.",
    price: 1450000,
    images: ["/products/sofa-cloud.jpg"],
    specs: { Modules: "4", Layout: "L", Fill: "High-resilience foam and fibre" },
    colors: [{ name: "Oatmeal bouclé", hex: "#E6DCCB" }],
    sizes: ["4-module L"],
    dimensions: "320 × 210 × 72 cm",
    material: "Bouclé, hardwood",
    stock: 2,
    warranty: wFrame,
    featured: true,
    newArrival: true,
  },
  {
    id: "nyanya-corduroy",
    categoryId: "sofas",
    name: "Rust Corduroy Three-Seater",
    description: "Three-seater in wide-wale rust corduroy with low rounded arms and black metal legs. One sofa. A warmer alternative to the linen three-seaters.",
    price: 315000,
    images: ["/products/sofa-corduroy.jpg"],
    specs: { Seating: "3-seater", Fabric: "Wide-wale corduroy", Legs: "Black metal" },
    colors: [{ name: "Rust corduroy", hex: "#A24A32" }],
    sizes: ["3-seater"],
    dimensions: "210 × 92 × 80 cm",
    material: "Corduroy, metal legs",
    stock: 5,
    warranty: wFrame,
    newArrival: true,
  },
  {
    id: "garki-cane-lounge",
    categoryId: "sofas",
    name: "Rattan and Linen Lounge Sofa",
    description: "Three-seater with an open honey rattan frame and thick cream linen cushions. For a veranda, a sunroom, or a sitting room that wants air through the back. Cushions are included.",
    price: 275000,
    images: ["/products/sofa-cane.jpg"],
    specs: { Seating: "3-seater", Frame: "Rattan cane", Cushions: "Cream linen, included" },
    colors: [{ name: "Honey cane / cream", hex: "#C4A574" }],
    sizes: ["3-seater"],
    dimensions: "200 × 85 × 78 cm",
    material: "Rattan, linen cushions",
    stock: 4,
    warranty: wFrame,
    newArrival: true,
  },
  {
    id: "kubwa-u-sectional",
    categoryId: "sofas",
    name: "Cream U-Sectional",
    description: "U-shaped sectional in cream linen with a chaise at each end. Seats about seven for a Sunday gathering. Low arms, deep seats. One connected piece, not three loose sofas.",
    price: 1680000,
    images: ["/products/sofa-u-cream.jpg"],
    specs: { Layout: "U-shape, chaise both ends", Seating: "7", Fabric: "Cream linen" },
    colors: [{ name: "Cream linen", hex: "#E7E0D4" }],
    sizes: ["U-shape"],
    dimensions: "360 × 220 × 82 cm",
    material: "Linen blend, hardwood",
    stock: 2,
    warranty: wFrame,
    featured: true,
  },
  {
    id: "lugbe-recliner-corner",
    categoryId: "sofas",
    name: "Charcoal Recliner Corner Sofa",
    description: "Charcoal fabric L-shaped recliner. The end seats have a manual lever and a footrest that comes forward; the corner seats stay fixed. Not an electric massage sofa.",
    price: 1250000,
    images: ["/products/sofa-power-corner.jpg"],
    specs: { Layout: "L-shape", Recline: "Manual lever on end seats", Seating: "5–6" },
    colors: [{ name: "Charcoal", hex: "#3A3A3A" }],
    sizes: ["Corner"],
    dimensions: "290 × 200 × 100 cm",
    material: "Woven fabric, hardwood and steel mechanism",
    stock: 2,
    warranty: wFrame,
    specialOffer: true,
    newArrival: true,
  },
  {
    id: "olive-chaise",
    categoryId: "sofas",
    name: "Olive Velvet Chaise",
    description: "A single chaise lounge in olive velvet with a cylindrical bolster and tapered walnut legs. One seat, for the end of a room or beside a bed. Not a sectional.",
    price: 185000,
    images: ["/products/chaise-olive.jpg"],
    specs: { Type: "Chaise lounge", Sold: "Single", Bolster: "Included" },
    colors: [{ name: "Olive velvet", hex: "#4E5A3A" }],
    sizes: ["Single"],
    dimensions: "170 × 75 × 78 cm",
    material: "Velvet, walnut",
    stock: 5,
    warranty: wFrame,
    newArrival: true,
  },
  {
    id: "carrara-marble-six",
    categoryId: "dining-sets",
    name: "Carrara Marble 6-Seater",
    description: "Rectangular white marble top with grey veining on a brushed-brass base, sold with six cream upholstered chairs on brass legs. A mid-showroom marble set, not a printed laminate. The plant in the photograph is not included.",
    price: 1480000,
    compareAt: 1650000,
    images: ["/products/dining-marble-white.jpg"],
    specs: { Seats: "6", Top: "White marble, grey vein", Base: "Brushed brass", Chairs: "6, cream upholstered" },
    colors: [{ name: "White marble / brass", hex: "#E7E1D6" }],
    sizes: ["6-seater"],
    dimensions: "Table 180 × 90 × 76 cm",
    material: "Marble, brass, fabric chairs",
    stock: 3,
    warranty: w24,
    featured: true,
    bestseller: true,
    specialOffer: true,
  },
  {
    id: "noir-marble-eight",
    categoryId: "dining-sets",
    name: "Noir Marble 8-Seater",
    description: "Long black marble top with white veins on a brass frame, sold with eight black upholstered chairs on brass legs. The sideboard, vase and bowl in the showroom photograph are not included. Extra chairs styled in the room are not part of the set.",
    price: 2150000,
    images: ["/products/dining-marble-black.jpg"],
    specs: { Seats: "8 included", Top: "Black marble, white vein", Frame: "Brass", Chairs: "8" },
    colors: [{ name: "Black marble / brass", hex: "#1A1A1A" }],
    sizes: ["8-seater"],
    dimensions: "Table 220 × 100 × 76 cm",
    material: "Marble, brass, fabric chairs",
    stock: 2,
    warranty: w24,
    featured: true,
    newArrival: true,
  },
  {
    id: "grey-marble-round",
    categoryId: "dining-sets",
    name: "Grey Marble Round 4-Seater",
    description: "Round white marble top with grey veining on a solid oak pedestal, sold with exactly four greige upholstered chairs. Sized for an apartment dining room.",
    price: 890000,
    images: ["/products/dining-marble-round.jpg"],
    specs: { Seats: "4", Shape: "Round", Top: "Grey-veined marble", Base: "Oak pedestal" },
    colors: [{ name: "Grey marble / oak", hex: "#D5D0C8" }],
    sizes: ["4-seater"],
    dimensions: "Table 120 cm diameter × 76 cm",
    material: "Marble, oak, fabric chairs",
    stock: 4,
    warranty: w24,
    newArrival: true,
  },
  {
    id: "travertine-six",
    categoryId: "dining-sets",
    name: "Travertine 6-Seater Dining Set",
    description: "Beige travertine stone top on a thick oak trestle, sold with six walnut chairs that have cane backs and cream seats. Stone, not a printed oak table.",
    price: 1280000,
    images: ["/products/dining-travertine.jpg"],
    specs: { Seats: "6", Top: "Travertine", Base: "Oak trestle", Chairs: "Walnut, cane back" },
    colors: [{ name: "Beige stone / walnut", hex: "#C4B49A" }],
    sizes: ["6-seater"],
    dimensions: "Table 180 × 90 × 76 cm",
    material: "Travertine, oak, cane",
    stock: 3,
    warranty: w24,
    featured: true,
  },
  {
    id: "marble-extend-six",
    categoryId: "dining-sets",
    name: "Extendable Marble 6-to-8 Set",
    description: "White marble top on a walnut trestle. The top splits so the table opens from six seats to eight. Sold with six charcoal upholstered chairs on walnut legs. The plant, books and vase are not included.",
    price: 1720000,
    compareAt: 1890000,
    images: ["/products/dining-marble-extend.jpg"],
    specs: { Seats: "6 chairs, opens to 8", Top: "White marble, splits", Base: "Walnut trestle" },
    colors: [{ name: "White marble / walnut", hex: "#E8E2D8" }],
    sizes: ["6-to-8"],
    dimensions: "160 cm closed, about 200 cm open",
    material: "Marble, walnut, fabric chairs",
    stock: 2,
    warranty: w24,
    specialOffer: true,
    newArrival: true,
  },
  {
    id: "walnut-dressing-table",
    categoryId: "bedroom-storage",
    name: "Walnut Dressing Table",
    description: "Walnut dressing table with three drawers, an oval mirror and a matching upholstered stool. The bedroom piece Nigerian homes still ask for after the wardrobe. Mirror and stool are included.",
    price: 165000,
    images: ["/products/dressing-table.jpg"],
    specs: { Drawers: "3", Mirror: "Oval, included", Stool: "Included" },
    colors: [{ name: "Walnut", hex: "#6B4226" }],
    sizes: ["120 cm"],
    dimensions: "120 × 45 × 150 cm with mirror",
    material: "Walnut veneer, fabric stool",
    stock: 6,
    warranty: w12,
    featured: true,
    newArrival: true,
  },
  {
    id: "walnut-chest",
    categoryId: "bedroom-storage",
    name: "Walnut Five-Drawer Chest",
    description: "Tall chest of five full-width drawers in walnut, with slim brass bar pulls. Stands beside a bed. Not a wardrobe and not a sideboard.",
    price: 128000,
    images: ["/products/chest-drawers.jpg"],
    specs: { Drawers: "5", Hardware: "Brass bar pulls" },
    colors: [{ name: "Walnut", hex: "#5C4033" }],
    sizes: ["90 cm"],
    dimensions: "90 × 48 × 120 cm",
    material: "Walnut veneer, engineered wood",
    stock: 7,
    warranty: w12,
    newArrival: true,
  },
  {
    id: "karu-shoe-cabinet",
    categoryId: "cabinets",
    name: "Oak Shoe Cabinet",
    description: "Low hallway cabinet with an oak top and four tilt-out compartments. Holds everyday shoes off the floor of a flat. Not a sideboard.",
    price: 72000,
    images: ["/products/shoe-cabinet.jpg"],
    specs: { Compartments: "4 tilt-out", Top: "Oak" },
    colors: [{ name: "White / oak", hex: "#F4F0EA" }],
    sizes: ["120 cm"],
    dimensions: "120 × 28 × 62 cm",
    material: "Painted board, oak top",
    stock: 10,
    warranty: w12,
    bestseller: true,
  },
  {
    id: "marble-centre-set",
    categoryId: "tables",
    name: "Marble Centre Table Set",
    description: "The centre-table set that completes a Nigerian sitting room: one rectangular white marble coffee table and two smaller round side stools on brass bases. Sold together. Not a dining table.",
    price: 245000,
    images: ["/products/centre-set.jpg"],
    specs: { Set: "1 centre table + 2 side stools", Top: "White marble", Base: "Brass" },
    colors: [{ name: "White marble / brass", hex: "#E7E1D6" }],
    sizes: ["3-piece"],
    dimensions: "Centre 120 × 60 × 40 cm",
    material: "Marble, brass",
    stock: 6,
    warranty: w12,
    featured: true,
    newArrival: true,
  },
  {
    id: "oak-bunk",
    categoryId: "beds",
    name: "Oak Bunk Bed",
    description: "Solid oak bunk with a ladder on the right and a rail on the top bunk. Two ivory foam mattresses are included. For a children's room. Not a pair of single beds.",
    price: 265000,
    images: ["/products/bunk-oak.jpg"],
    specs: { Sleeps: "2", Mattress: "Two foam mattresses included", Ladder: "Right side" },
    colors: [{ name: "Natural oak", hex: "#C19A6B" }],
    sizes: ["Single over single"],
    dimensions: "200 × 105 × 160 cm",
    material: "Solid oak, foam mattresses",
    stock: 4,
    warranty: "5-year structural warranty. 12 months on the mattresses.",
    newArrival: true,
  },
  {
    id: "calm-massage-chair",
    categoryId: "chairs",
    name: "Calm Leather Massage Chair",
    description: "Cream leather zero-gravity massage chair with the footrest closed. One chair for a quiet corner. Not a sofa and not a dining chair. A hand controller is in the box.",
    price: 485000,
    images: ["/products/massage-chair.jpg"],
    specs: { Type: "Massage chair", Recline: "Zero gravity", Cover: "Cream leather" },
    colors: [{ name: "Cream leather", hex: "#E8E0D4" }],
    sizes: ["Single"],
    dimensions: "80 × 110 × 115 cm upright",
    material: "Leather, steel mechanism",
    stock: 3,
    warranty: w24,
    newArrival: true,
    featured: true,
  },
  {
    id: "oak-dining-bench",
    categoryId: "chairs",
    name: "Oak Dining Bench",
    description: "A long oak bench with a cream upholstered seat. Seats two or three along one side of a dining table. Sold on its own. The table is not included.",
    price: 95000,
    images: ["/products/dining-bench.jpg"],
    specs: { Seats: "2–3", Seat: "Cream upholstered", Table: "Not included" },
    colors: [{ name: "Oak / cream", hex: "#E6DCCE" }],
    sizes: ["160 cm"],
    dimensions: "160 × 40 × 48 cm",
    material: "Oak, fabric",
    stock: 8,
    warranty: w12,
  },
  {
    id: "royal-highback-chair",
    categoryId: "chairs",
    name: "Royal High-Back Chair",
    description: "One royal chair: a tall carved gilt frame, crest rail, scrolled arms and a burgundy velvet seat and back. Sold singly. Not a sofa and not a dining side chair.",
    price: 185000,
    images: ["/products/chair-royal.jpg"],
    specs: { Type: "Royal chair", Frame: "Carved gilt wood", Upholstery: "Burgundy velvet", Sold: "Single" },
    colors: [{ name: "Burgundy / gilt", hex: "#6E1E33" }],
    sizes: ["Single"],
    dimensions: "78 × 70 × 128 cm",
    material: "Carved wood, velvet",
    stock: 6,
    warranty: wFrame,
    featured: true,
    newArrival: true,
  },
  {
    id: "royal-chair-pair",
    categoryId: "chairs",
    name: "Royal Chair Pair",
    description: "Two matching royal chairs in emerald velvet on carved gilt frames, with crest rails and scrolled arms. Sold as the pair. A table shown beside them is not included.",
    price: 340000,
    compareAt: 380000,
    images: ["/products/chair-royal-pair.jpg"],
    specs: { Type: "Royal chair", Pack: "Pair", Frame: "Carved gilt wood", Upholstery: "Emerald velvet" },
    colors: [{ name: "Emerald / gilt", hex: "#1E4D3A" }],
    sizes: ["Pair"],
    dimensions: "Each 76 × 68 × 126 cm",
    material: "Carved wood, velvet",
    stock: 4,
    warranty: wFrame,
    bestseller: true,
    specialOffer: true,
  },
  {
    id: "wingback-armchair",
    categoryId: "chairs",
    name: "Wingback Armchair",
    description: "A single wingback in forest velvet, with high winged sides, a tight back, brass nailheads and dark walnut legs. One chair.",
    price: 165000,
    images: ["/products/chair-wingback.jpg"],
    specs: { Type: "Wingback", Legs: "Walnut", Trim: "Brass nailhead" },
    colors: [{ name: "Forest velvet", hex: "#1E3A2F" }],
    sizes: ["Single"],
    dimensions: "78 × 80 × 104 cm",
    material: "Velvet, walnut",
    stock: 5,
    warranty: wFrame,
    newArrival: true,
  },
  {
    id: "chesterfield-armchair",
    categoryId: "chairs",
    name: "Chesterfield Armchair",
    description: "One Chesterfield armchair in cognac leather. Deep button tufting, rolled arms and dark turned legs. A chair, not the three-seater Chesterfield sofa.",
    price: 195000,
    images: ["/products/chair-chesterfield.jpg"],
    specs: { Type: "Chesterfield armchair", Leather: "Cognac", Sold: "Single" },
    colors: [{ name: "Cognac leather", hex: "#8A4B24" }],
    sizes: ["Single"],
    dimensions: "86 × 82 × 78 cm",
    material: "Leather, hardwood",
    stock: 4,
    warranty: wFrame,
    featured: true,
  },
  {
    id: "walnut-rocking-chair",
    categoryId: "chairs",
    name: "Walnut Rocking Chair",
    description: "A walnut rocking chair with a spindle back, a woven cane seat and curved rockers. One chair.",
    price: 98000,
    images: ["/products/chair-rocker.jpg"],
    specs: { Type: "Rocking chair", Seat: "Cane", Wood: "Walnut" },
    colors: [{ name: "Walnut", hex: "#6B4226" }],
    sizes: ["Single"],
    dimensions: "68 × 90 × 102 cm",
    material: "Walnut, cane",
    stock: 7,
    warranty: w12,
  },
  {
    id: "cream-swivel-chair",
    categoryId: "chairs",
    name: "Cream Leather Swivel Chair",
    description: "A low cream leather lounge chair on a brushed-metal swivel pedestal. One chair. It turns. It is not a sofa.",
    price: 210000,
    images: ["/products/chair-swivel.jpg"],
    specs: { Type: "Swivel lounge", Base: "Brushed metal pedestal", Cover: "Cream leather" },
    colors: [{ name: "Cream leather", hex: "#E8E0D4" }],
    sizes: ["Single"],
    dimensions: "82 × 82 × 76 cm",
    material: "Leather, metal",
    stock: 4,
    warranty: wFrame,
    newArrival: true,
  },
  {
    id: "oak-carver-chair",
    categoryId: "chairs",
    name: "Oak Carver Dining Chair",
    description: "One dining carver: a solid oak armchair with a greige upholstered seat and back, for the head of a table. Sold singly. The table is not included.",
    price: 72000,
    images: ["/products/chair-carver.jpg"],
    specs: { Type: "Carver", Frame: "Oak", Seat: "Greige upholstered", Sold: "Single" },
    colors: [{ name: "Oak / greige", hex: "#C4A574" }],
    sizes: ["Single"],
    dimensions: "58 × 60 × 96 cm",
    material: "Oak, linen blend",
    stock: 10,
    warranty: w12,
    bestseller: true,
  },
  {
    id: "blush-slipper-chair",
    categoryId: "chairs",
    name: "Blush Velvet Slipper Chair",
    description: "A low armless slipper chair in blush velvet with a scooped back and dark tapered legs. One chair, for a dressing corner or the end of a bed.",
    price: 89000,
    images: ["/products/chair-slipper.jpg"],
    specs: { Type: "Slipper chair", Arms: "None", Legs: "Dark tapered wood" },
    colors: [{ name: "Blush velvet", hex: "#C9A3A8" }],
    sizes: ["Single"],
    dimensions: "62 × 68 × 74 cm",
    material: "Velvet, wood",
    stock: 6,
    warranty: wFrame,
    newArrival: true,
  },
];

export const SEED_BANNERS: SeedBanner[] = [
  {
    title: "Living rooms, properly made",
    subtitle: "3+2+1 sitting-room sets, corner sofas and marble dining, on the floor in Karu.",
    imageUrl: "/banners/living-hero.jpg",
    ctaText: "Shop furniture",
    ctaHref: "/categories/furniture",
    sortOrder: 1,
  },
  {
    title: "The working kitchen",
    subtitle: "A stainless side-by-side refrigerator, a freestanding gas range, and a countertop microwave — each sold on its own.",
    imageUrl: "/banners/kitchen-hero.jpg",
    ctaText: "Shop appliances",
    ctaHref: "/categories/appliances",
    sortOrder: 2,
  },
  {
    title: "Picture and sound, sold honestly",
    subtitle: "Televisions from 32 to 75 inches. Soundbars and floor speakers live in their own category, or together as a cinema set.",
    imageUrl: "/products/cinema-55.jpg",
    ctaText: "Shop electronics",
    ctaHref: "/categories/electronics",
    sortOrder: 3,
  },
];

export const PRODUCT_DELIVERY = DEFAULT_DELIVERY;

export const ADVANCED_IDS = [
  "maitama-power-sofa",
  "garki-storage-bed",
  "hybridrest-king",
  "round-oak-dining",
  "nest-centre-tables",
  "cognac-lounge-set",
  "floor-media-console",
  "glass-vitrine",
  "lift-standing-desk",
  "brass-sconce-pair",
  "frostpeak-sbs",
  "chillvault-wide",
  "aquacycle-stack",
  "flamehaus-six",
  "breezeline-tower",
  "breezeline-black",
  "forge-espresso",
  "clearwell-dishwasher",
  "sweep-robot",
  "helios-75",
  "nile-satellites",
  "pulse-party",
  "lumen-projector",
  "mesh-pair",
  "wuse-curve-sofa",
  "ivory-mirror-wardrobe",
  "oak-open-wardrobe",
  "oak-bedside-pair",
  "oak-dining-eight",
  "jabi-bookcase",
  "linen-drum-pendant",
  "frostpeak-black",
  "chillvault-slim",
  "aquacycle-combo",
  "flamehaus-five",
  "heatwave-white",
  "millhouse-rice",
  "forge-iron",
  "crestline-32",
  "nile-slim-bar",
  "grove-floor",
  "cinema-55-set",
  "articulate-mount",
  "studio-buds",
  "gwarinpa-chenille-set",
  "lugbe-leather-set",
  "maitama-chesterfield",
  "jikwoyi-corner",
  "asokoro-velvet-set",
  "karu-sofa-bed",
  "wuse-cloud-modular",
  "nyanya-corduroy",
  "garki-cane-lounge",
  "kubwa-u-sectional",
  "lugbe-recliner-corner",
  "olive-chaise",
  "carrara-marble-six",
  "noir-marble-eight",
  "grey-marble-round",
  "travertine-six",
  "marble-extend-six",
  "walnut-dressing-table",
  "walnut-chest",
  "karu-shoe-cabinet",
  "marble-centre-set",
  "oak-bunk",
  "calm-massage-chair",
  "oak-dining-bench",
] as const;

export const SITTING_IDS = [
  "gwarinpa-chenille-set",
  "lugbe-leather-set",
  "asokoro-velvet-set",
  "jikwoyi-corner",
  "kubwa-u-sectional",
  "wuse-cloud-modular",
  "maitama-chesterfield",
  "lugbe-recliner-corner",
  "karu-sofa-bed",
  "nyanya-corduroy",
  "garki-cane-lounge",
  "olive-chaise",
] as const;

export const MARBLE_IDS = [
  "carrara-marble-six",
  "noir-marble-eight",
  "travertine-six",
  "marble-extend-six",
  "grey-marble-round",
  "marble-centre-set",
] as const;

export const EXTENDED_IDS = [
  "wuse-curve-sofa",
  "ivory-mirror-wardrobe",
  "oak-open-wardrobe",
  "oak-bedside-pair",
  "oak-dining-eight",
  "jabi-bookcase",
  "linen-drum-pendant",
  "frostpeak-black",
  "chillvault-slim",
  "aquacycle-combo",
  "flamehaus-five",
  "heatwave-white",
  "millhouse-rice",
  "forge-iron",
  "crestline-32",
  "nile-slim-bar",
  "grove-floor",
  "cinema-55-set",
  "articulate-mount",
  "studio-buds",
] as const;

export function categoryById(id: string) {
  return SEED_CATEGORIES.find((c) => c.id === id) ?? null;
}
